// Bundles lodash's own test suite (test/test.js of lodash 4.17.21, run by
// QUnit 2 and qunit-extras) into one script that Nona compiles. Nona has no
// CommonJS `require`, so each file becomes a module function behind a small
// loader. Node.js built-in modules (fs, path, vm) are not provided: the suite
// only uses them inside lodashStable.attempt or try blocks.
//
//   node build-tests.mjs <lodash source checkout> [output.js]
//
// The checkout needs node_modules/lodash (the "stable" copy the suite compares
// against), node_modules/qunitjs and node_modules/qunit-extras.
import {readFileSync, writeFileSync} from 'node:fs';
import {join, resolve} from 'node:path';

const root = resolve(process.argv[2] ?? '.');
const output = process.argv[3] ?? 'lodash-tests.js';
const modules = {
  'qunitjs': 'node_modules/qunitjs/qunit/qunit.js',
  'qunit-extras': 'node_modules/qunit-extras/qunit-extras.js',
  '../node_modules/lodash/lodash.js': 'node_modules/lodash/lodash.js',
  '../lodash.js': 'lodash.js',
  './test.js': 'test/test.js',
};
let bundle = `// Generated by examples/lodash/build-tests.mjs from ${Object.values(modules).join(', ')}.
var global = globalThis;
var __definitions = {}, __cache = {};
function __require(id) {
  if (Object.prototype.hasOwnProperty.call(__cache, id)) return __cache[id].exports;
  if (!Object.prototype.hasOwnProperty.call(__definitions, id)) throw new Error("Cannot find module '" + id + "'");
  var module = __cache[id] = {exports: {}};
  __definitions[id].call(module.exports, module, module.exports, __require);
  return module.exports;
}
__require.resolve = function (id) {
  if (Object.prototype.hasOwnProperty.call(__definitions, id)) return id;
  throw new Error("Cannot find module '" + id + "'");
};
`;
for (const [id, file] of Object.entries(modules))
  bundle += `__definitions[${JSON.stringify(id)}] = function (module, exports, require) {\n${readFileSync(join(root, file), 'utf8')}\n};\n`;
bundle += `__require('./test.js');\n`;
writeFileSync(output, bundle);
console.log(`${output}: ${(bundle.length / 1e6).toFixed(2)} MB`);
