import {RuntimeBuilder,slot} from './abi.js';
import {rootedFn} from './root-scope.js';
import {stringLiteral} from './value.js';
import {ObjectLayout as O,PropertyLayout as P,PropertyAttributes as A} from './object-layout.js';
import {BoxKind,BoxLayout} from './boxing.js';
import {emitFunctionBuiltin,prependFunctionBuiltin,builtinPropertyRoots} from './function-builtin.js';

export const bigintRoots=['rt.bigintToString.fn','rt.bigintValueOf.fn','rt.BigInt.asIntN.fn','rt.BigInt.asUintN.fn'];
export const bigintPropertyRoots=['rt.bigintPrototype.@@toStringTag',...builtinPropertyRoots('rt.bigintToString.fn','toString','rt.bigintPrototype'),...builtinPropertyRoots('rt.bigintValueOf.fn','valueOf','rt.bigintPrototype'),...builtinPropertyRoots('rt.BigInt.asIntN.fn','asIntN','rt.BigInt'),...builtinPropertyRoots('rt.BigInt.asUintN.fn','asUintN','rt.BigInt')];

export function emitBigInt(b:RuntimeBuilder):void {
 b.bundle.fragments.push(stringLiteral('rt.bigint.minus','-'));
 b.bundle.fragments.push(stringLiteral('rt.bigint.zero','0'));
 b.bundle.fragments.push(stringLiteral('rt.bigint.two','2'),stringLiteral('rt.bigint.minusone','-1'));
 // RDX Value* -> RAX low 64 bits of ToBigInt(value). Number is deliberately rejected.
 rootedFn(b,'rt.bigintToUint64',136,[{kind:'value',register:'rdx'},{kind:'locals',offset:64,count:2}],a=>{
  for(const n of [0,8]){a.load('rax',{base:'rdx',disp:n});a.store(slot(64+n),'rax');}a.mov('rax',0);a.store(slot(120),'rax');
  const inspect=a.unique('inspect'),object=a.unique('object'),string=a.unique('string'),boolean=a.unique('boolean'),parse=a.unique('parse'),positive=a.unique('positive'),loop=a.unique('loop'),end=a.unique('end');
  a.label(inspect);a.load('rax',slot(64));a.cmp('rax',7);a.jcc('e',parse);a.cmp('rax',5);a.jcc('e',object);a.cmp('rax',4);a.jcc('e',string);a.cmp('rax',2);a.jcc('e',boolean);a.call('rt.throwTypeError');
  a.label(object);a.lea('rcx',slot(80));a.lea('rdx',slot(64));a.call('rt.objectToPrimitiveNumber');for(const n of [0,8]){a.load('rax',slot(80+n));a.store(slot(64+n),'rax');}a.jmp(inspect);
  a.label(string);a.lea('rcx',slot(80));a.load('rdx',slot(72));a.mov('r8',0);a.call('rt.bigintFromDecimal');for(const n of [0,8]){a.load('rax',slot(80+n));a.store(slot(64+n),'rax');}a.jmp(parse);
  a.label(boolean);a.load('rax',slot(72));a.store(slot(96),'rax');a.jmp(end);
  a.label(parse);a.load('r10',slot(72));a.load('rax',{base:'r10'});a.store(slot(112),'rax');a.mov('rax',0);a.store(slot(96),'rax');a.store(slot(104),'rax');a.store(slot(120),'rax');
  a.load('r11',{base:'r10',disp:8},16);a.cmp('r11',45);a.jcc('ne',positive);a.mov('rax',1);a.store(slot(104),'rax');a.store(slot(120),'rax');a.label(positive);
  a.label(loop);a.load('rax',slot(104));a.load('r10',slot(112));a.cmp('rax','r10');a.jcc('ae',end);a.shl('rax',1);a.load('r10',slot(72));a.add('r10','rax');a.load('r11',{base:'r10',disp:8},16);a.sub('r11',48);a.load('rax',slot(96));a.mov('r10',10);a.imul('rax','r10');a.add('rax','r11');a.store(slot(96),'rax');a.load('rax',slot(104));a.add('rax',1);a.store(slot(104),'rax');a.jmp(loop);
  a.label(end);a.load('rax',slot(96));a.load('r10',slot(120));a.test('r10','r10');const result=a.unique('result');a.jcc('e',result);a.neg('rax');a.label(result);
 });
 // RDX raw bits, R8 signed flag -> RCX BigInt Value*. The decimal string is exact.
 rootedFn(b,'rt.uint64ToBigInt',136,[{kind:'output',register:'rcx'},{kind:'locals',offset:64,count:1}],a=>{
  a.store(slot(40),'rcx');a.store(slot(48),'rdx');a.store(slot(56),'r8');a.mov('rax',0);a.store(slot(80),'rax');a.store(slot(96),'rax');
  a.load('rax',slot(56));a.test('rax','rax');const magnitude=a.unique('magnitude'),write=a.unique('write');a.jcc('e',magnitude);a.load('rax',slot(48));a.cmp('rax',0);a.jcc('ge',magnitude);a.mov('rax',1);a.store(slot(80),'rax');a.load('rax',slot(48));a.neg('rax');a.store(slot(48),'rax');a.label(magnitude);
  a.mov('rcx',50);a.call('rt.alloc');a.mov('r10',7);a.store(slot(64),'r10');a.store(slot(72),'rax');
  a.label(write);a.load('rax',slot(48));a.xor('rdx','rdx');a.mov('r10',10);a.div('r10');a.store(slot(48),'rax');a.add('rdx',48);a.load('r10',slot(96));a.shl('r10',1);a.load('r11',slot(72));a.add('r11','r10');a.store({base:'r11',disp:8},'rdx',16);a.load('rax',slot(96));a.add('rax',1);a.store(slot(96),'rax');a.load('rax',slot(48));a.test('rax','rax');a.jcc('ne',write);
  a.load('rax',slot(80));a.test('rax','rax');const reverse=a.unique('reverse');a.jcc('e',reverse);a.load('rax',slot(96));a.shl('rax',1);a.load('r10',slot(72));a.add('r10','rax');a.mov('rax',45);a.store({base:'r10',disp:8},'rax',16);a.load('rax',slot(96));a.add('rax',1);a.store(slot(96),'rax');a.label(reverse);
  a.load('r10',slot(72));a.load('rax',slot(96));a.store({base:'r10'},'rax');a.mov('r8',0);a.load('r9',slot(96));a.sub('r9',1);const swap=a.unique('swap'),done=a.unique('done');a.label(swap);a.cmp('r8','r9');a.jcc('ae',done);a.mov('r10','r8');a.shl('r10',1);a.load('rax',slot(72));a.add('r10','rax');a.mov('r11','r9');a.shl('r11',1);a.add('r11','rax');a.load('rax',{base:'r10',disp:8},16);a.load('rdx',{base:'r11',disp:8},16);a.store({base:'r10',disp:8},'rdx',16);a.store({base:'r11',disp:8},'rax',16);a.add('r8',1);a.sub('r9',1);a.jmp(swap);a.label(done);
  a.load('rcx',slot(40));for(const n of [0,8]){a.load('rax',slot(64+n));a.store({base:'rcx',disp:n},'rax');}
 });
 rootedFn(b,'rt.bigintNeg',136,[{kind:'output',register:'rcx'},{kind:'value',register:'rdx'},{kind:'locals',offset:64,count:3}],a=>{
  a.store(slot(40),'rcx');a.mov('rax',7);a.store(slot(64),'rax');a.load('rax',{base:'rdx',disp:8});a.store(slot(72),'rax');a.load('r10',{base:'rax'});
  const zero=a.unique('zero'),negative=a.unique('negative'),done=a.unique('done');a.cmp('r10',1);a.jcc('ne','rt.bigintNeg.sign');a.load('r11',{base:'rax',disp:8},16);a.cmp('r11',48);a.jcc('e',zero);
  a.label('rt.bigintNeg.sign');a.load('r11',{base:'rax',disp:8},16);a.cmp('r11',45);a.jcc('e',negative);
  a.mov('rax',4);a.store(slot(80),'rax');a.lea('rax',{rip:'rt.bigint.minus'});a.store(slot(88),'rax');a.mov('rax',4);a.store(slot(96),'rax');a.load('rax',slot(72));a.store(slot(104),'rax');
  a.lea('rcx',slot(112));a.lea('rdx',slot(80));a.lea('r8',slot(96));a.call('rt.concat');a.jmp(done);
  a.label(negative);a.lea('rcx',slot(112));a.load('rdx',slot(72));a.mov('r8',1);a.mov('r9','r10');a.call('rt.jsonSlice');a.jmp(done);
  a.label(zero);a.mov('rax',4);a.store(slot(112),'rax');a.load('rax',slot(72));a.store(slot(120),'rax');
  a.label(done);a.load('rcx',slot(40));a.mov('rax',7);a.store({base:'rcx'},'rax');a.load('rax',slot(120));a.store({base:'rcx',disp:8},'rax');
 });
 rootedFn(b,'rt.bigintAdd',280,[{kind:'output',register:'rcx'},{kind:'value',register:'rdx'},{kind:'value',register:'r8'},{kind:'locals',offset:80,count:3}],a=>{
  a.store(slot(40),'rcx');for(const n of [0,8]){a.load('rax',{base:'rdx',disp:n});a.store(slot(80+n),'rax');a.load('rax',{base:'r8',disp:n});a.store(slot(96+n),'rax');}
  for(const [base,length,sign,start] of [[88,128,144,160],[104,136,152,168]] as const){a.load('r10',slot(base));a.load('rax',{base:'r10'});a.store(slot(length),'rax');a.load('rax',{base:'r10',disp:8},16);a.cmp('rax',45);const positive=a.unique('positive'),ready=a.unique('ready');a.jcc('ne',positive);a.mov('rax',1);a.store(slot(sign),'rax');a.store(slot(start),'rax');a.jmp(ready);a.label(positive);a.mov('rax',0);a.store(slot(sign),'rax');a.store(slot(start),'rax');a.label(ready);}
  a.load('rax',slot(144));a.load('r10',slot(152));a.cmp('rax','r10');const sameSign=a.unique('sameSign'),ordered=a.unique('ordered'),compare=a.unique('compare'),compareLoop=a.unique('compareLoop'),swap=a.unique('swap'),zero=a.unique('zero');a.jcc('e',sameSign);
  a.mov('rax',1);a.store(slot(192),'rax');a.load('rax',slot(128));a.load('r11',slot(160));a.sub('rax','r11');a.load('r10',slot(136));a.load('r11',slot(168));a.sub('r10','r11');a.cmp('rax','r10');a.jcc('b',swap);a.jcc('a',ordered);a.mov('rax',0);a.store(slot(256),'rax');a.label(compareLoop);
  a.load('rax',slot(256));a.load('r10',slot(128));a.load('r11',slot(160));a.sub('r10','r11');a.cmp('rax','r10');a.jcc('ae',zero);
  a.load('r10',slot(160));a.add('r10','rax');a.shl('r10',1);a.load('r11',slot(88));a.add('r11','r10');a.load('r11',{base:'r11',disp:8},16);
  a.load('r10',slot(168));a.add('r10','rax');a.shl('r10',1);a.load('rdx',slot(104));a.add('rdx','r10');a.load('rdx',{base:'rdx',disp:8},16);a.cmp('r11','rdx');a.jcc('b',swap);a.jcc('a',ordered);a.load('rax',slot(256));a.add('rax',1);a.store(slot(256),'rax');a.jmp(compareLoop);
  a.label(swap);for(const [left,right] of [[80,96],[88,104],[128,136],[144,152],[160,168]] as const){a.load('rax',slot(left));a.load('r10',slot(right));a.store(slot(left),'r10');a.store(slot(right),'rax');}a.jmp(ordered);
  a.label(sameSign);a.mov('rax',0);a.store(slot(192),'rax');a.label(ordered);a.load('rax',slot(144));a.store(slot(224),'rax');
  a.load('rax',slot(128));a.load('r11',slot(160));a.sub('rax','r11');a.load('r10',slot(136));a.load('r11',slot(168));a.sub('r10','r11');a.cmp('rax','r10');const capacity=a.unique('capacity');a.jcc('ae',capacity);a.mov('rax','r10');a.label(capacity);a.add('rax',2);a.store(slot(216),'rax');a.mov('rcx','rax');a.shl('rcx',1);a.add('rcx',8);a.call('rt.alloc');a.mov('r10',4);a.store(slot(112),'r10');a.store(slot(120),'rax');a.load('r10',slot(216));a.store({base:'rax'},'r10');
  a.load('rax',slot(128));a.sub('rax',1);a.store(slot(176),'rax');a.load('rax',slot(136));a.sub('rax',1);a.store(slot(184),'rax');a.load('rax',slot(216));a.sub('rax',1);a.store(slot(208),'rax');a.mov('rax',0);a.store(slot(200),'rax');
  const loop=a.unique('loop'),digits=a.unique('digits'),readB=a.unique('readB'),calculate=a.unique('calculate'),subtract=a.unique('subtract'),write=a.unique('write'),finish=a.unique('finish');a.label(loop);
  a.load('rax',slot(176));a.load('r10',slot(160));a.cmp('rax','r10');a.jcc('ge',digits);a.load('rax',slot(184));a.load('r10',slot(168));a.cmp('rax','r10');a.jcc('ge',digits);a.load('rax',slot(200));a.test('rax','rax');a.jcc('e',finish);
  a.label(digits);a.mov('rax',0);a.store(slot(232),'rax');a.store(slot(240),'rax');a.load('rax',slot(176));a.load('r10',slot(160));a.cmp('rax','r10');a.jcc('l',readB);a.shl('rax',1);a.load('r10',slot(88));a.add('r10','rax');a.load('rax',{base:'r10',disp:8},16);a.sub('rax',48);a.store(slot(232),'rax');
  a.label(readB);a.load('rax',slot(184));a.load('r10',slot(168));a.cmp('rax','r10');a.jcc('l',calculate);a.shl('rax',1);a.load('r10',slot(104));a.add('r10','rax');a.load('rax',{base:'r10',disp:8},16);a.sub('rax',48);a.store(slot(240),'rax');
  a.label(calculate);a.load('rax',slot(192));a.test('rax','rax');a.jcc('ne',subtract);a.load('rax',slot(232));a.load('r11',slot(240));a.add('rax','r11');a.load('r11',slot(200));a.add('rax','r11');a.mov('r10',0);a.cmp('rax',10);a.jcc('b',write);a.sub('rax',10);a.mov('r10',1);a.jmp(write);
  a.label(subtract);a.load('rax',slot(232));a.load('r11',slot(240));a.sub('rax','r11');a.load('r11',slot(200));a.sub('rax','r11');a.mov('r10',0);a.cmp('rax',0);a.jcc('ge',write);a.add('rax',10);a.mov('r10',1);
  a.label(write);a.store(slot(200),'r10');a.add('rax',48);a.load('r10',slot(208));a.shl('r10',1);a.load('r11',slot(120));a.add('r11','r10');a.store({base:'r11',disp:8},'rax',16);for(const index of [176,184,208]){a.load('rax',slot(index));a.sub('rax',1);a.store(slot(index),'rax');}a.jmp(loop);
  a.label(finish);a.load('rax',slot(208));a.add('rax',1);a.store(slot(248),'rax');const trim=a.unique('trim'),trimDone=a.unique('trimDone');a.label(trim);a.load('rax',slot(248));a.load('r10',slot(216));a.sub('r10',1);a.cmp('rax','r10');a.jcc('ae',trimDone);a.shl('rax',1);a.load('r10',slot(120));a.add('r10','rax');a.load('r11',{base:'r10',disp:8},16);a.cmp('r11',48);a.jcc('ne',trimDone);a.load('rax',slot(248));a.add('rax',1);a.store(slot(248),'rax');a.jmp(trim);a.label(trimDone);
  a.load('rax',slot(248));a.load('r10',slot(216));a.sub('r10',1);a.cmp('rax','r10');const nonzero=a.unique('nonzero');a.jcc('ne',nonzero);a.shl('rax',1);a.load('r10',slot(120));a.add('r10','rax');a.load('r11',{base:'r10',disp:8},16);a.cmp('r11',48);a.jcc('e',zero);
  a.label(nonzero);a.load('rax',slot(224));a.test('rax','rax');const slice=a.unique('slice');a.jcc('e',slice);a.load('rax',slot(248));a.sub('rax',1);a.store(slot(248),'rax');a.shl('rax',1);a.load('r10',slot(120));a.add('r10','rax');a.mov('rax',45);a.store({base:'r10',disp:8},'rax',16);
  a.label(slice);a.lea('rcx',slot(112));a.load('rdx',slot(120));a.load('r8',slot(248));a.load('r9',slot(216));a.call('rt.jsonSlice');a.jmp('rt.bigintAdd.return');
  a.label(zero);a.mov('rax',4);a.store(slot(112),'rax');a.lea('rax',{rip:'rt.bigint.zero'});a.store(slot(120),'rax');
  a.label('rt.bigintAdd.return');a.load('rcx',slot(40));a.mov('rax',7);a.store({base:'rcx'},'rax');a.load('rax',slot(120));a.store({base:'rcx',disp:8},'rax');
 });
 rootedFn(b,'rt.bigintFromDecimal',200,[{kind:'output',register:'rcx'},{kind:'locals',offset:64,count:3}],a=>{
  a.store(slot(40),'rcx');a.store(slot(168),'r8');a.mov('rax',4);a.store(slot(64),'rax');a.store(slot(72),'rdx');a.mov('rax',0);a.store(slot(112),'rax');a.load('rax',{base:'rdx'});a.store(slot(120),'rax');
  const white=(label:string)=>{for(const c of [9,10,11,12,13,32,0xa0,0x1680,0x2028,0x2029,0x202f,0x205f,0x3000,0xfeff]){a.cmp('r11',c);a.jcc('e',label);}a.cmp('r11',0x2000);const other=a.unique('other');a.jcc('b',other);a.cmp('r11',0x200a);a.jcc('be',label);a.label(other);};
  const left=a.unique('left'),leftNext=a.unique('leftNext'),right=a.unique('right'),rightNext=a.unique('rightNext'),sign=a.unique('sign'),invalid=a.unique('invalid'),zero=a.unique('zero'),done=a.unique('done');
  a.label(left);a.load('rax',slot(112));a.load('r10',slot(120));a.cmp('rax','r10');a.jcc('ae',zero);a.shl('rax',1);a.load('r10',slot(72));a.add('r10','rax');a.load('r11',{base:'r10',disp:8},16);white(leftNext);a.jmp(right);a.label(leftNext);a.load('rax',slot(112));a.add('rax',1);a.store(slot(112),'rax');a.jmp(left);
  a.label(right);a.load('rax',slot(120));a.load('r10',slot(112));a.cmp('rax','r10');a.jcc('be',zero);a.sub('rax',1);a.shl('rax',1);a.load('r10',slot(72));a.add('r10','rax');a.load('r11',{base:'r10',disp:8},16);white(rightNext);a.jmp(sign);a.label(rightNext);a.load('rax',slot(120));a.sub('rax',1);a.store(slot(120),'rax');a.jmp(right);
  a.label(sign);a.load('rax',slot(120));a.load('r10',slot(112));a.sub('rax','r10');a.cmp('rax',3);const decimal=a.unique('decimal');a.jcc('b',decimal);
  a.load('rax',slot(112));a.shl('rax',1);a.load('r10',slot(72));a.add('r10','rax');a.load('r11',{base:'r10',disp:8},16);a.cmp('r11',48);a.jcc('ne',decimal);a.load('r11',{base:'r10',disp:10},16);
  const hex=a.unique('hex'),binary=a.unique('binary'),octal=a.unique('octal'),prefixReady=a.unique('prefixReady');for(const code of [120,88]){a.cmp('r11',code);a.jcc('e',hex);}for(const code of [98,66]){a.cmp('r11',code);a.jcc('e',binary);}for(const code of [111,79]){a.cmp('r11',code);a.jcc('e',octal);}a.jmp(decimal);
  a.label(hex);a.mov('rax',16);a.jmp(prefixReady);a.label(binary);a.mov('rax',2);a.jmp(prefixReady);a.label(octal);a.mov('rax',8);a.label(prefixReady);a.store(slot(152),'rax');a.mov('rax',7);a.store(slot(80),'rax');a.lea('rax',{rip:'rt.bigint.zero'});a.store(slot(88),'rax');a.load('rax',slot(112));a.add('rax',2);a.store(slot(160),'rax');
  const prefixLoop=a.unique('prefixLoop'),prefixDone=a.unique('prefixDone'),prefixLower=a.unique('prefixLower'),digitReady=a.unique('digitReady');a.label(prefixLoop);a.load('rax',slot(160));a.load('r10',slot(120));a.cmp('rax','r10');a.jcc('ae',prefixDone);a.shl('rax',1);a.load('r10',slot(72));a.add('r10','rax');a.load('r11',{base:'r10',disp:8},16);
  a.cmp('r11',48);a.jcc('b',invalid);a.cmp('r11',57);a.jcc('a',prefixLower);a.sub('r11',48);a.jmp(digitReady);
  a.label(prefixLower);a.cmp('r11',65);a.jcc('b',invalid);a.cmp('r11',70);const lowercase=a.unique('lowercase');a.jcc('a',lowercase);a.sub('r11',55);a.jmp(digitReady);a.label(lowercase);a.cmp('r11',97);a.jcc('b',invalid);a.cmp('r11',102);a.jcc('a',invalid);a.sub('r11',87);
  a.label(digitReady);a.load('rax',slot(152));a.cmp('r11','rax');a.jcc('ae',invalid);a.lea('rcx',slot(80));a.lea('rdx',slot(80));a.mov('r8','rax');a.mov('r9','r11');a.call('rt.bigintScaleDigit');a.load('rax',slot(160));a.add('rax',1);a.store(slot(160),'rax');a.jmp(prefixLoop);
  a.label(prefixDone);a.jmp(done);
  a.label(decimal);a.mov('rax',0);a.store(slot(128),'rax');a.load('rax',slot(112));a.shl('rax',1);a.load('r10',slot(72));a.add('r10','rax');a.load('r11',{base:'r10',disp:8},16);a.cmp('r11',45);const plus=a.unique('plus'),digits=a.unique('digits');a.jcc('ne',plus);a.mov('rax',1);a.store(slot(128),'rax');a.jmp('rt.bigintFromDecimal.skipSign');a.label(plus);a.cmp('r11',43);a.jcc('ne',digits);a.label('rt.bigintFromDecimal.skipSign');a.load('rax',slot(112));a.add('rax',1);a.store(slot(112),'rax');
  a.label(digits);a.load('rax',slot(112));a.load('r10',slot(120));a.cmp('rax','r10');a.jcc('ae',invalid);a.store(slot(136),'rax');a.mov('r10',-1);a.store(slot(144),'r10');const scan=a.unique('scan'),next=a.unique('next'),scanDone=a.unique('scanDone');a.label(scan);a.load('rax',slot(136));a.load('r10',slot(120));a.cmp('rax','r10');a.jcc('ae',scanDone);a.shl('rax',1);a.load('r10',slot(72));a.add('r10','rax');a.load('r11',{base:'r10',disp:8},16);a.cmp('r11',48);a.jcc('b',invalid);a.cmp('r11',57);a.jcc('a',invalid);a.cmp('r11',48);a.jcc('e',next);a.load('r10',slot(144));a.cmp('r10',-1);a.jcc('ne',next);a.load('rax',slot(136));a.store(slot(144),'rax');a.label(next);a.load('rax',slot(136));a.add('rax',1);a.store(slot(136),'rax');a.jmp(scan);
  a.label(scanDone);a.load('rax',slot(144));a.cmp('rax',-1);a.jcc('e',zero);a.lea('rcx',slot(80));a.load('rdx',slot(72));a.mov('r8','rax');a.load('r9',slot(120));a.call('rt.jsonSlice');a.load('rax',slot(128));a.test('rax','rax');a.jcc('e',done);
  a.mov('rax',4);a.store(slot(96),'rax');a.lea('rax',{rip:'rt.bigint.minus'});a.store(slot(104),'rax');a.lea('rcx',slot(80));a.lea('rdx',slot(96));a.lea('r8',slot(80));a.call('rt.concat');a.jmp(done);
  a.label(zero);a.mov('rax',4);a.store(slot(80),'rax');a.lea('rax',{rip:'rt.bigint.zero'});a.store(slot(88),'rax');a.jmp(done);
  a.label(invalid);a.load('rax',slot(168));a.test('rax','rax');const hardError=a.unique('hardError'),end=a.unique('end');a.jcc('e',hardError);a.load('rcx',slot(40));a.mov('rax',0);a.store({base:'rcx'},'rax');a.store({base:'rcx',disp:8},'rax');a.jmp(end);a.label(hardError);a.call('rt.throwSyntaxError');a.label(done);a.load('rcx',slot(40));a.mov('rax',7);a.store({base:'rcx'},'rax');a.load('rax',slot(88));a.store({base:'rcx',disp:8},'rax');a.label(end);
 });
 rootedFn(b,'rt.bigintFromDoubleInteger',168,[{kind:'output',register:'rcx'},{kind:'value',register:'rdx'},{kind:'locals',offset:64,count:2}],a=>{
  a.store(slot(40),'rcx');a.load('rax',{base:'rdx',disp:8});a.mov('r10','rax');a.shr('r10',63);a.store(slot(112),'r10');a.mov('r11',0x000fffffffffffffn);a.and('r11','rax');a.store(slot(128),'r11');a.shr('rax',52);a.and('rax',0x7ff);const normal=a.unique('normal'),zero=a.unique('zero'),invalid=a.unique('invalid'),ready=a.unique('ready');a.test('rax','rax');a.jcc('ne',normal);a.test('r11','r11');a.jcc('e',zero);a.jmp(invalid);a.label(normal);a.cmp('rax',0x7ff);a.jcc('e',invalid);a.sub('rax',1075);a.store(slot(120),'rax');a.load('r11',slot(128));a.mov('r10',0x0010000000000000n);a.or('r11','r10');a.store(slot(128),'r11');a.cmp('rax',0);const nonnegative=a.unique('nonnegative');a.jcc('ge',nonnegative);a.neg('rax');a.cmp('rax',52);a.jcc('a',invalid);a.mov('rcx','rax');a.mov('r10',1);a.shl('r10','cl');a.sub('r10',1);a.and('r10','r11');a.test('r10','r10');a.jcc('ne',invalid);a.shr('r11','cl');a.store(slot(128),'r11');a.mov('rax',0);a.store(slot(120),'rax');a.label(nonnegative);
  a.mov('rax',3);a.store(slot(80),'rax');a.load('rax',slot(128));a.cvtsi2sd('xmm0','rax');a.storesd(slot(88),'xmm0');a.lea('rcx',slot(64));a.lea('rdx',slot(80));a.call('rt.toString');a.load('rdx',slot(72));a.lea('rcx',slot(64));a.mov('r8',0);a.call('rt.bigintFromDecimal');a.mov('rax',0);a.store(slot(136),'rax');const loop=a.unique('loop'),scaled=a.unique('scaled');a.label(loop);a.load('rax',slot(136));a.load('r10',slot(120));a.cmp('rax','r10');a.jcc('ae',scaled);a.lea('rcx',slot(64));a.lea('rdx',slot(64));a.mov('r8',2);a.mov('r9',0);a.call('rt.bigintScaleDigit');a.load('rax',slot(136));a.add('rax',1);a.store(slot(136),'rax');a.jmp(loop);a.label(scaled);a.load('rax',slot(112));a.test('rax','rax');a.jcc('e',ready);a.lea('rcx',slot(80));a.lea('rdx',slot(64));a.call('rt.bigintNeg');for(const offset of [0,8]){a.load('rax',slot(80+offset));a.store(slot(64+offset),'rax');}a.jmp(ready);
  a.label(zero);a.mov('rax',7);a.store(slot(64),'rax');a.lea('rax',{rip:'rt.bigint.zero'});a.store(slot(72),'rax');a.jmp(ready);a.label(invalid);a.call('rt.throwRangeError');a.label(ready);a.load('rcx',slot(40));for(const offset of [0,8]){a.load('rax',slot(64+offset));a.store({base:'rcx',disp:offset},'rax');}
 });
 // Multiply a nonnegative decimal BigInt by a radix <= 16 and add one digit.
 rootedFn(b,'rt.bigintScaleDigit',168,[{kind:'output',register:'rcx'},{kind:'value',register:'rdx'},{kind:'locals',offset:64,count:2}],a=>{
  a.store(slot(40),'rcx');a.mov('rax',7);a.store(slot(64),'rax');a.load('rax',{base:'rdx',disp:8});a.store(slot(72),'rax');a.store(slot(96),'r8');a.store(slot(104),'r9');a.load('rax',{base:'rax'});a.store(slot(112),'rax');a.add('rax',3);a.store(slot(144),'rax');a.mov('rcx','rax');a.shl('rcx',1);a.add('rcx',8);a.call('rt.alloc');a.mov('r10',4);a.store(slot(80),'r10');a.store(slot(88),'rax');a.load('r10',slot(144));a.store({base:'rax'},'r10');
  a.load('rax',slot(112));a.sub('rax',1);a.store(slot(120),'rax');a.load('rax',slot(144));a.sub('rax',1);a.store(slot(128),'rax');a.load('rax',slot(104));a.store(slot(136),'rax');
  const loop=a.unique('loop'),digit=a.unique('digit'),emit=a.unique('emit'),done=a.unique('done');a.label(loop);a.load('rax',slot(120));a.cmp('rax',0);a.jcc('ge',digit);a.load('rax',slot(136));a.test('rax','rax');a.jcc('e',done);a.jmp(emit);
  a.label(digit);a.shl('rax',1);a.load('r10',slot(72));a.add('r10','rax');a.load('rax',{base:'r10',disp:8},16);a.sub('rax',48);a.load('r10',slot(96));a.imul('rax','r10');a.load('r10',slot(136));a.add('rax','r10');
  a.label(emit);a.xor('rdx','rdx');a.mov('r10',10);a.div('r10');a.store(slot(136),'rax');a.add('rdx',48);a.load('r10',slot(128));a.shl('r10',1);a.load('r11',slot(88));a.add('r11','r10');a.store({base:'r11',disp:8},'rdx',16);for(const offset of [120,128]){a.load('rax',slot(offset));a.sub('rax',1);a.store(slot(offset),'rax');}a.jmp(loop);
  a.label(done);a.load('rax',slot(128));a.add('rax',1);a.store(slot(152),'rax');a.lea('rcx',slot(80));a.load('rdx',slot(88));a.mov('r8','rax');a.load('r9',slot(144));a.call('rt.jsonSlice');a.load('rcx',slot(40));a.mov('rax',7);a.store({base:'rcx'},'rax');a.load('rax',slot(88));a.store({base:'rcx',disp:8},'rax');
 });
 b.fn('rt.bigintCompareMagnitude',40,a=>{
  a.load('rcx',{base:'rcx',disp:8});a.load('rdx',{base:'rdx',disp:8});a.load('r10',{base:'rcx'});a.load('r11',{base:'rdx'});a.cmp('r10','r11');const less=a.unique('less'),greater=a.unique('greater'),done=a.unique('done');a.jcc('b',less);a.jcc('a',greater);a.call('rt.compareStrings');a.jmp(done);a.label(less);a.mov('rax',-1);a.jmp(done);a.label(greater);a.mov('rax',1);a.label(done);
 });
 b.fn('rt.bigintCompareSigned',88,a=>{
  a.load('rcx',{base:'rcx',disp:8});a.load('rdx',{base:'rdx',disp:8});a.load('r8',{base:'rcx'});a.load('r9',{base:'rdx'});a.mov('rax',0);a.store(slot(56),'rax');a.store(slot(64),'rax');a.load('r10',{base:'rcx',disp:8},16);const leftPositive=a.unique('leftPositive');a.cmp('r10',45);a.jcc('ne',leftPositive);a.mov('rax',1);a.store(slot(56),'rax');a.sub('r8',1);a.label(leftPositive);a.load('r10',{base:'rdx',disp:8},16);const rightPositive=a.unique('rightPositive');a.cmp('r10',45);a.jcc('ne',rightPositive);a.mov('rax',1);a.store(slot(64),'rax');a.sub('r9',1);a.label(rightPositive);a.load('rax',slot(56));a.load('r10',slot(64));a.cmp('rax','r10');const sameSign=a.unique('sameSign'),less=a.unique('less'),greater=a.unique('greater'),finish=a.unique('finish'),signDiff=a.unique('signDiff');a.jcc('e',sameSign);a.test('rax','rax');a.jcc('ne',signDiff);a.mov('rax',1);a.jmp(finish);a.label(signDiff);a.mov('rax',-1);a.jmp(finish);
  a.label(sameSign);a.cmp('r8','r9');a.jcc('b',less);a.jcc('a',greater);a.mov('rax',0);a.store(slot(72),'rax');const loop=a.unique('loop'),equal=a.unique('equal');a.label(loop);a.load('rax',slot(72));a.cmp('rax','r8');a.jcc('ae',equal);a.load('r10',slot(56));a.add('r10','rax');a.shl('r10',1);a.add('r10','rcx');a.load('r11',{base:'r10',disp:8},16);a.load('r10',slot(64));a.add('r10','rax');a.shl('r10',1);a.add('r10','rdx');a.load('r10',{base:'r10',disp:8},16);a.cmp('r11','r10');a.jcc('b',less);a.jcc('a',greater);a.load('rax',slot(72));a.add('rax',1);a.store(slot(72),'rax');a.jmp(loop);
  a.label(equal);a.mov('rax',0);a.jmp(finish);a.label(less);a.mov('rax',-1);a.jmp('rt.bigintCompareSigned.sign');a.label(greater);a.mov('rax',1);a.label('rt.bigintCompareSigned.sign');a.load('r10',slot(56));a.test('r10','r10');a.jcc('e',finish);a.neg('rax');a.label(finish);
 });
 rootedFn(b,'rt.bigintCompareNumber',200,[{kind:'value',register:'rdx'},{kind:'value',register:'r8'},{kind:'locals',offset:64,count:2}],a=>{
  a.store(slot(40),'rdx');a.store(slot(48),'r8');a.mov('rax',0);a.store(slot(128),'rax');a.movsd('xmm0',{base:'r8',disp:8});a.ucomisd('xmm0','xmm0');const nan=a.unique('nan'),infinity=a.unique('infinity'),wide=a.unique('wide'),convert=a.unique('convert'),done=a.unique('done');a.jcc('p',nan);a.load('rax',{base:'r8',disp:8});a.mov('r10','rax');a.shr('r10',52);a.and('r10',0x7ff);a.cmp('r10',0x7ff);a.jcc('e',infinity);
  a.mov('rax',0x43e0000000000000n);a.movqToXmm('xmm1','rax');a.ucomisd('xmm0','xmm1');a.jcc('ae',wide);a.mov('rax',0xc3e0000000000000n);a.movqToXmm('xmm1','rax');a.ucomisd('xmm0','xmm1');a.jcc('b',wide);a.cvttsd2si('rax','xmm0');a.cvtsi2sd('xmm1','rax');a.ucomisd('xmm0','xmm1');const fractionalPositive=a.unique('fractionalPositive'),fractionalNegative=a.unique('fractionalNegative'),integerReady=a.unique('integerReady');a.jcc('a',fractionalPositive);a.jcc('b',fractionalNegative);a.jmp(integerReady);a.label(fractionalPositive);a.mov('r10',1);a.store(slot(128),'r10');a.jmp(integerReady);a.label(fractionalNegative);a.mov('r10',-1);a.store(slot(128),'r10');a.label(integerReady);a.cvtsi2sd('xmm1','rax');a.mov('r10',3);a.store(slot(64),'r10');a.storesd(slot(72),'xmm1');a.jmp(convert);
  a.label(wide);a.load('r10',slot(48));for(const offset of [0,8]){a.load('rax',{base:'r10',disp:offset});a.store(slot(64+offset),'rax');}a.label(convert);a.lea('rcx',slot(80));a.lea('rdx',slot(64));a.call('rt.bigintFromDoubleInteger');a.load('rcx',slot(40));a.lea('rdx',slot(80));a.call('rt.bigintCompareSigned');a.test('rax','rax');a.jcc('ne',done);a.load('rax',slot(128));a.neg('rax');a.jmp(done);
  a.label(infinity);a.load('r10',slot(48));a.load('rax',{base:'r10',disp:8});a.shr('rax',63);a.test('rax','rax');const positiveInfinity=a.unique('positiveInfinity');a.jcc('e',positiveInfinity);a.mov('rax',1);a.jmp(done);a.label(positiveInfinity);a.mov('rax',-1);a.jmp(done);a.label(nan);a.mov('rax',2);a.label(done);
 });
 rootedFn(b,'rt.bigintCompareString',120,[{kind:'value',register:'rdx'},{kind:'value',register:'r8'},{kind:'locals',offset:64,count:1}],a=>{
  a.store(slot(40),'rdx');a.load('rdx',{base:'r8',disp:8});a.lea('rcx',slot(64));a.mov('r8',1);a.call('rt.bigintFromDecimal');a.load('rax',slot(64));const valid=a.unique('valid'),done=a.unique('done');a.cmp('rax',7);a.jcc('e',valid);a.mov('rax',2);a.jmp(done);a.label(valid);a.load('rcx',slot(40));a.lea('rdx',slot(64));a.call('rt.bigintCompareSigned');a.label(done);
 });
 // rt.bigintMul: see bigint-mul.ts.
 rootedFn(b,'rt.bigintDivRem',280,[{kind:'output',register:'rcx'},{kind:'value',register:'rdx'},{kind:'value',register:'r8'},{kind:'locals',offset:64,count:7}],a=>{
  a.store(slot(40),'rcx');a.store(slot(48),'rdx');a.store(slot(56),'r8');a.store(slot(224),'r9');a.mov('rax',0);a.store(slot(184),'rax');a.store(slot(192),'rax');
  for(const [source,target,sign] of [[48,64,184],[56,80,192]] as const){a.load('r10',slot(source));a.load('r10',{base:'r10',disp:8});a.load('rax',{base:'r10',disp:8},16);const positive=a.unique('positive'),ready=a.unique('ready');a.cmp('rax',45);a.jcc('ne',positive);a.mov('rax',1);a.store(slot(sign),'rax');a.lea('rcx',slot(target));a.load('rdx',slot(source));a.call('rt.bigintNeg');a.jmp(ready);a.label(positive);a.load('r10',slot(source));for(const offset of [0,8]){a.load('rax',{base:'r10',disp:offset});a.store(slot(target+offset),'rax');}a.label(ready);}
  a.load('r10',slot(88));a.load('rax',{base:'r10'});a.cmp('rax',1);const nonzero=a.unique('nonzero');a.jcc('ne',nonzero);a.load('rax',{base:'r10',disp:8},16);a.cmp('rax',48);a.jcc('ne',nonzero);a.call('rt.throwRangeError');a.label(nonzero);
  a.lea('rcx',slot(96));a.lea('rdx',slot(80));a.call('rt.bigintNeg');for(const offset of [112,128]){a.mov('rax',7);a.store(slot(offset),'rax');a.lea('rax',{rip:'rt.bigint.zero'});a.store(slot(offset+8),'rax');}
  a.lea('rcx',slot(144));a.lea('rdx',slot(64));a.mov('r8',2);a.call('rt.bigintToRadix');a.load('r10',slot(152));a.load('rax',{base:'r10'});a.store(slot(200),'rax');a.mov('rax',0);a.store(slot(208),'rax');
  const loop=a.unique('loop'),subtract=a.unique('subtract'),digitReady=a.unique('digitReady'),finish=a.unique('finish'),done=a.unique('done');a.label(loop);a.load('rax',slot(208));a.load('r10',slot(200));a.cmp('rax','r10');a.jcc('ae',finish);a.shl('rax',1);a.load('r10',slot(152));a.add('r10','rax');a.load('r9',{base:'r10',disp:8},16);a.sub('r9',48);a.lea('rcx',slot(112));a.lea('rdx',slot(112));a.mov('r8',2);a.call('rt.bigintScaleDigit');
  a.lea('rcx',slot(112));a.lea('rdx',slot(80));a.call('rt.bigintCompareMagnitude');a.cmp('rax',0);a.jcc('ge',subtract);a.mov('r9',0);a.jmp(digitReady);a.label(subtract);a.lea('rcx',slot(112));a.lea('rdx',slot(112));a.lea('r8',slot(96));a.call('rt.bigintAdd');a.mov('r9',1);a.label(digitReady);a.lea('rcx',slot(128));a.lea('rdx',slot(128));a.mov('r8',2);a.call('rt.bigintScaleDigit');a.load('rax',slot(208));a.add('rax',1);a.store(slot(208),'rax');a.jmp(loop);
  a.label(finish);a.load('rax',slot(224));a.test('rax','rax');const quotient=a.unique('quotient'),signReady=a.unique('signReady');a.jcc('e',quotient);for(const offset of [0,8]){a.load('rax',slot(112+offset));a.store(slot(160+offset),'rax');}a.load('rax',slot(184));a.jmp(signReady);a.label(quotient);for(const offset of [0,8]){a.load('rax',slot(128+offset));a.store(slot(160+offset),'rax');}a.load('rax',slot(184));a.load('r10',slot(192));a.xor('rax','r10');a.label(signReady);a.test('rax','rax');a.jcc('e',done);a.lea('rcx',slot(160));a.lea('rdx',slot(160));a.call('rt.bigintNeg');a.label(done);a.load('rcx',slot(40));for(const offset of [0,8]){a.load('rax',slot(160+offset));a.store({base:'rcx',disp:offset},'rax');}
 });
 rootedFn(b,'rt.bigintPow',200,[{kind:'output',register:'rcx'},{kind:'value',register:'rdx'},{kind:'value',register:'r8'},{kind:'locals',offset:64,count:3}],a=>{
  a.store(slot(40),'rcx');for(const offset of [0,8]){a.load('rax',{base:'rdx',disp:offset});a.store(slot(64+offset),'rax');}a.load('r10',{base:'r8',disp:8});a.load('rax',{base:'r10',disp:8},16);const valid=a.unique('valid');a.cmp('rax',45);a.jcc('ne',valid);a.call('rt.throwRangeError');a.label(valid);a.lea('rcx',slot(80));a.mov('rdx','r8');a.mov('r8',2);a.call('rt.bigintToRadix');a.mov('rax',7);a.store(slot(96),'rax');a.lea('rax',{rip:'rt.bigint.one'});a.store(slot(104),'rax');a.load('r10',slot(88));a.load('rax',{base:'r10'});a.store(slot(128),'rax');a.mov('rax',0);a.store(slot(136),'rax');
  const loop=a.unique('loop'),next=a.unique('next'),done=a.unique('done');a.label(loop);a.load('rax',slot(136));a.load('r10',slot(128));a.cmp('rax','r10');a.jcc('ae',done);a.lea('rcx',slot(96));a.lea('rdx',slot(96));a.lea('r8',slot(96));a.call('rt.bigintMul');a.load('rax',slot(136));a.shl('rax',1);a.load('r10',slot(88));a.add('r10','rax');a.load('rax',{base:'r10',disp:8},16);a.cmp('rax',49);a.jcc('ne',next);a.lea('rcx',slot(96));a.lea('rdx',slot(96));a.lea('r8',slot(64));a.call('rt.bigintMul');a.label(next);a.load('rax',slot(136));a.add('rax',1);a.store(slot(136),'rax');a.jmp(loop);
  a.label(done);a.load('rcx',slot(40));for(const offset of [0,8]){a.load('rax',slot(96+offset));a.store({base:'rcx',disp:offset},'rax');}
 });
 rootedFn(b,'rt.bigintShift',280,[{kind:'output',register:'rcx'},{kind:'value',register:'rdx'},{kind:'value',register:'r8'},{kind:'locals',offset:64,count:8}],a=>{
  a.store(slot(40),'rcx');for(const offset of [0,8]){a.load('rax',{base:'rdx',disp:offset});a.store(slot(64+offset),'rax');}a.store(slot(192),'r9');a.mov('rax',0);a.store(slot(200),'rax');a.load('r10',{base:'r8',disp:8});a.load('rax',{base:'r10',disp:8},16);const positive=a.unique('positive'),countReady=a.unique('countReady');a.cmp('rax',45);a.jcc('ne',positive);a.load('rax',slot(192));a.xor('rax',1);a.store(slot(192),'rax');a.lea('rcx',slot(80));a.mov('rdx','r8');a.call('rt.bigintNeg');a.jmp(countReady);a.label(positive);for(const offset of [0,8]){a.load('rax',{base:'r8',disp:offset});a.store(slot(80+offset),'rax');}a.label(countReady);
  const shortRight=a.unique('shortRight'),normalShift=a.unique('normalShift');a.load('rax',slot(192));a.test('rax','rax');a.jcc('e',normalShift);a.load('r10',slot(72));a.load('rax',{base:'r10',disp:8},16);a.mov('r11',0);a.cmp('rax',45);const positiveBase=a.unique('positiveBase');a.jcc('ne',positiveBase);a.mov('r11',1);a.label(positiveBase);a.store(slot(200),'r11');a.test('r11','r11');const magnitudeReady=a.unique('magnitudeReady'),magnitudeDone=a.unique('magnitudeDone');a.jcc('e',magnitudeReady);a.lea('rcx',slot(176));a.lea('rdx',slot(64));a.call('rt.bigintNeg');a.jmp(magnitudeDone);a.label(magnitudeReady);for(const offset of [0,8]){a.load('rax',slot(64+offset));a.store(slot(176+offset),'rax');}a.label(magnitudeDone);a.lea('rcx',slot(176));a.lea('rdx',slot(176));a.mov('r8',2);a.call('rt.bigintToRadix');a.load('r10',slot(184));a.load('rax',{base:'r10'});a.store(slot(208),'rax');a.load('rcx',slot(88));a.call('rt.parseNumber');a.load('rax',slot(208));a.cvtsi2sd('xmm1','rax');a.ucomisd('xmm0','xmm1');a.jcc('ae',shortRight);
  a.label(normalShift);a.mov('rax',7);a.store(slot(96),'rax');a.lea('rax',{rip:'rt.bigint.two'});a.store(slot(104),'rax');a.lea('rcx',slot(96));a.lea('rdx',slot(96));a.lea('r8',slot(80));a.call('rt.bigintPow');a.load('rax',slot(192));a.test('rax','rax');const right=a.unique('right'),done=a.unique('done');a.jcc('ne',right);a.lea('rcx',slot(144));a.lea('rdx',slot(64));a.lea('r8',slot(96));a.call('rt.bigintMul');a.jmp(done);
  a.label(right);a.lea('rcx',slot(112));a.lea('rdx',slot(64));a.lea('r8',slot(96));a.mov('r9',0);a.call('rt.bigintDivRem');a.lea('rcx',slot(128));a.lea('rdx',slot(64));a.lea('r8',slot(96));a.mov('r9',1);a.call('rt.bigintDivRem');a.load('r10',slot(72));a.load('rax',{base:'r10',disp:8},16);const copy=a.unique('copy');a.cmp('rax',45);a.jcc('ne',copy);a.load('r10',slot(136));a.load('rax',{base:'r10'});a.cmp('rax',1);a.jcc('ne','rt.bigintShift.adjust');a.load('rax',{base:'r10',disp:8},16);a.cmp('rax',48);a.jcc('e',copy);a.label('rt.bigintShift.adjust');a.mov('rax',7);a.store(slot(160),'rax');a.lea('rax',{rip:'rt.bigint.minusone'});a.store(slot(168),'rax');a.lea('rcx',slot(112));a.lea('rdx',slot(112));a.lea('r8',slot(160));a.call('rt.bigintAdd');a.label(copy);for(const offset of [0,8]){a.load('rax',slot(112+offset));a.store(slot(144+offset),'rax');}a.jmp(done);
  a.label(shortRight);a.mov('rax',7);a.store(slot(144),'rax');a.load('rax',slot(200));a.test('rax','rax');const positiveResult=a.unique('positiveResult');a.jcc('e',positiveResult);a.lea('rax',{rip:'rt.bigint.minusone'});a.jmp('rt.bigintShift.shortResult');a.label(positiveResult);a.lea('rax',{rip:'rt.bigint.zero'});a.label('rt.bigintShift.shortResult');a.store(slot(152),'rax');a.label(done);a.load('rcx',slot(40));for(const offset of [0,8]){a.load('rax',slot(144+offset));a.store({base:'rcx',disp:offset},'rax');}
 });
 rootedFn(b,'rt.bigintBitwise',280,[{kind:'output',register:'rcx'},{kind:'value',register:'rdx'},{kind:'value',register:'r8'},{kind:'locals',offset:64,count:8}],a=>{
  a.store(slot(40),'rcx');a.store(slot(216),'r9');for(const [source,target] of [['rdx',64],['r8',80]] as const)for(const offset of [0,8]){a.load('rax',{base:source,disp:offset});a.store(slot(target+offset),'rax');}
  a.load('r10',slot(72));a.load('rax',{base:'r10'});a.load('r10',slot(88));a.load('r11',{base:'r10'});a.cmp('rax','r11');const widthReady=a.unique('widthReady');a.jcc('ae',widthReady);a.mov('rax','r11');a.label(widthReady);a.shl('rax',2);a.add('rax',2);a.store(slot(208),'rax');
  for(const [source,target] of [[64,96],[80,112]] as const){a.lea('rcx',slot(target));a.load('rdx',slot(208));a.lea('r8',slot(source));a.mov('r9',0);a.call('rt.bigintAsN');}
  for(const [source,target,len] of [[96,128,232],[112,144,240]] as const){a.lea('rcx',slot(target));a.lea('rdx',slot(source));a.mov('r8',2);a.call('rt.bigintToRadix');a.load('r10',slot(target+8));a.load('rax',{base:'r10'});a.store(slot(len),'rax');}
  a.mov('rax',7);a.store(slot(160),'rax');a.lea('rax',{rip:'rt.bigint.zero'});a.store(slot(168),'rax');a.load('rax',slot(208));a.sub('rax',1);a.store(slot(224),'rax');
  const readBit=(descriptor:number,length:number,result:number)=>{const zero=a.unique('zero'),ready=a.unique('ready');a.load('rax',slot(224));a.load('r11',slot(length));a.cmp('rax','r11');a.jcc('ae',zero);a.sub('r11','rax');a.sub('r11',1);a.shl('r11',1);a.load('r10',slot(descriptor));a.add('r10','r11');a.load(result===248?'rax':'r9',{base:'r10',disp:8},16);if(result===248)a.sub('rax',48);else a.sub('r9',48);a.jmp(ready);a.label(zero);if(result===248)a.mov('rax',0);else a.mov('r9',0);a.label(ready);if(result===248)a.store(slot(248),'rax');};
  const loop=a.unique('loop'),finish=a.unique('finish');a.label(loop);a.load('rax',slot(224));a.cmp('rax',0);a.jcc('l',finish);readBit(136,232,248);readBit(152,240,0);a.load('rax',slot(248));a.load('r10',slot(216));a.cmp('r10',0);const bitAnd=a.unique('bitAnd'),bitOr=a.unique('bitOr'),combine=a.unique('combine');a.jcc('e',bitAnd);a.cmp('r10',1);a.jcc('e',bitOr);a.xor('rax','r9');a.jmp(combine);a.label(bitAnd);a.and('rax','r9');a.jmp(combine);a.label(bitOr);a.or('rax','r9');a.label(combine);a.lea('rcx',slot(160));a.lea('rdx',slot(160));a.mov('r8',2);a.mov('r9','rax');a.call('rt.bigintScaleDigit');a.load('rax',slot(224));a.sub('rax',1);a.store(slot(224),'rax');a.jmp(loop);
  a.label(finish);a.lea('rcx',slot(176));a.load('rdx',slot(208));a.lea('r8',slot(160));a.mov('r9',1);a.call('rt.bigintAsN');a.load('rcx',slot(40));for(const offset of [0,8]){a.load('rax',slot(176+offset));a.store({base:'rcx',disp:offset},'rax');}
 });
 rootedFn(b,'rt.bigintAsN',312,[{kind:'output',register:'rcx'},{kind:'value',register:'r8'},{kind:'locals',offset:64,count:8}],a=>{
  a.store(slot(40),'rcx');a.store(slot(200),'rdx');a.store(slot(208),'r9');for(const offset of [0,8]){a.load('rax',{base:'r8',disp:offset});a.store(slot(64+offset),'rax');}
  a.mov('rax',0);a.store(slot(216),'rax');a.load('r10',slot(72));a.load('rax',{base:'r10',disp:8},16);const positive=a.unique('positive'),absoluteReady=a.unique('absoluteReady'),returnInput=a.unique('returnInput'),returnZero=a.unique('returnZero'),done=a.unique('done');a.cmp('rax',45);a.jcc('ne',positive);a.mov('rax',1);a.store(slot(216),'rax');a.lea('rcx',slot(80));a.lea('rdx',slot(64));a.call('rt.bigintNeg');a.jmp(absoluteReady);a.label(positive);for(const offset of [0,8]){a.load('rax',slot(64+offset));a.store(slot(80+offset),'rax');}a.label(absoluteReady);
  a.load('rax',slot(200));a.test('rax','rax');a.jcc('e',returnZero);a.lea('rcx',slot(96));a.lea('rdx',slot(80));a.mov('r8',2);a.call('rt.bigintToRadix');a.load('r10',slot(104));a.load('rax',{base:'r10'});a.store(slot(232),'rax');a.load('r11',slot(200));a.cmp('r11','rax');const truncate=a.unique('truncate');a.jcc('b',truncate);a.load('r11',slot(216));a.test('r11','r11');const needsModulo=a.unique('needsModulo');a.jcc('ne',needsModulo);a.load('r11',slot(208));a.test('r11','r11');a.jcc('e',returnInput);a.load('r11',slot(200));a.cmp('r11','rax');a.jcc('a',returnInput);a.jmp(truncate);a.label(needsModulo);a.load('r11',slot(208));a.test('r11','r11');a.jcc('e',truncate);a.load('r11',slot(200));a.cmp('r11','rax');a.jcc('a',returnInput);
  a.label(truncate);a.mov('rax',7);a.store(slot(112),'rax');a.lea('rax',{rip:'rt.bigint.zero'});a.store(slot(120),'rax');a.load('rax',slot(232));a.load('r10',slot(200));a.cmp('rax','r10');const startReady=a.unique('startReady');a.jcc('be',startReady);a.sub('rax','r10');a.jmp('rt.bigintAsN.startStored');a.label(startReady);a.mov('rax',0);a.label('rt.bigintAsN.startStored');a.store(slot(224),'rax');
  const parse=a.unique('parse'),parseDone=a.unique('parseDone');a.label(parse);a.load('rax',slot(224));a.load('r10',slot(232));a.cmp('rax','r10');a.jcc('ae',parseDone);a.shl('rax',1);a.load('r10',slot(104));a.add('r10','rax');a.load('r9',{base:'r10',disp:8},16);a.sub('r9',48);a.lea('rcx',slot(112));a.lea('rdx',slot(112));a.mov('r8',2);a.call('rt.bigintScaleDigit');a.load('rax',slot(224));a.add('rax',1);a.store(slot(224),'rax');a.jmp(parse);a.label(parseDone);
  a.load('r10',slot(120));a.load('rax',{base:'r10',disp:8},16);a.cmp('rax',48);a.jcc('e',returnZero);
  // For unsigned negative values and signed overflows, construct 2^bits.
  a.mov('rax',7);a.store(slot(128),'rax');a.lea('rax',{rip:'rt.bigint.one'});a.store(slot(136),'rax');a.mov('rax',0);a.store(slot(240),'rax');const power=a.unique('power'),powerReady=a.unique('powerReady');a.label(power);a.load('rax',slot(240));a.load('r10',slot(200));a.cmp('rax','r10');a.jcc('ae',powerReady);a.lea('rcx',slot(128));a.lea('rdx',slot(128));a.mov('r8',2);a.mov('r9',0);a.call('rt.bigintScaleDigit');a.load('rax',slot(240));a.add('rax',1);a.store(slot(240),'rax');a.jmp(power);a.label(powerReady);
  a.load('rax',slot(216));a.test('rax','rax');const unsignedReady=a.unique('unsignedReady');a.jcc('e',unsignedReady);a.lea('rcx',slot(144));a.lea('rdx',slot(112));a.call('rt.bigintNeg');a.lea('rcx',slot(160));a.lea('rdx',slot(128));a.lea('r8',slot(144));a.call('rt.bigintAdd');for(const offset of [0,8]){a.load('rax',slot(160+offset));a.store(slot(112+offset),'rax');}a.label(unsignedReady);
  a.load('rax',slot(208));a.test('rax','rax');a.jcc('e','rt.bigintAsN.result');
  // Half the range is 2^(bits-1); signed values at or above it wrap.
  a.mov('rax',7);a.store(slot(176),'rax');a.lea('rax',{rip:'rt.bigint.one'});a.store(slot(184),'rax');a.mov('rax',1);a.store(slot(240),'rax');const half=a.unique('half'),halfReady=a.unique('halfReady');a.label(half);a.load('rax',slot(240));a.load('r10',slot(200));a.cmp('rax','r10');a.jcc('ae',halfReady);a.lea('rcx',slot(176));a.lea('rdx',slot(176));a.mov('r8',2);a.mov('r9',0);a.call('rt.bigintScaleDigit');a.load('rax',slot(240));a.add('rax',1);a.store(slot(240),'rax');a.jmp(half);a.label(halfReady);
  a.lea('rcx',slot(112));a.lea('rdx',slot(176));a.call('rt.bigintCompareMagnitude');a.cmp('rax',0);a.jcc('l','rt.bigintAsN.result');a.lea('rcx',slot(144));a.lea('rdx',slot(128));a.call('rt.bigintNeg');a.lea('rcx',slot(160));a.lea('rdx',slot(112));a.lea('r8',slot(144));a.call('rt.bigintAdd');for(const offset of [0,8]){a.load('rax',slot(160+offset));a.store(slot(112+offset),'rax');}
  a.label('rt.bigintAsN.result');a.load('rcx',slot(40));for(const offset of [0,8]){a.load('rax',slot(112+offset));a.store({base:'rcx',disp:offset},'rax');}a.jmp(done);
  a.label(returnInput);a.load('rcx',slot(40));for(const offset of [0,8]){a.load('rax',slot(64+offset));a.store({base:'rcx',disp:offset},'rax');}a.jmp(done);
  a.label(returnZero);a.load('rcx',slot(40));a.mov('rax',7);a.store({base:'rcx'},'rax');a.lea('rax',{rip:'rt.bigint.zero'});a.store({base:'rcx',disp:8},'rax');a.label(done);
 });
 b.fn('rt.BigInt.construct',40,a=>a.call('rt.throwTypeError'));
 rootedFn(b,'rt.BigInt.code',120,[{kind:'output',register:'rcx'},{kind:'range',register:'r8',count:'rdx'},{kind:'locals',offset:64,count:2}],a=>{
  a.store(slot(40),'rcx');a.test('rdx','rdx');const supplied=a.unique('supplied');a.jcc('ne',supplied);a.call('rt.throwTypeError');a.label(supplied);for(const n of [0,8]){a.load('rax',{base:'r8',disp:n});a.store(slot(64+n),'rax');}
  const inspect=a.unique('inspect'),boolean=a.unique('boolean'),number=a.unique('number'),string=a.unique('string'),done=a.unique('done');a.label(inspect);a.load('rax',slot(64));a.cmp('rax',7);a.jcc('e',done);a.cmp('rax',2);a.jcc('e',boolean);a.cmp('rax',3);a.jcc('e',number);a.cmp('rax',4);a.jcc('e',string);a.cmp('rax',5);const object=a.unique('object');a.jcc('e',object);a.call('rt.throwTypeError');
  a.label(object);a.lea('rcx',slot(80));a.lea('rdx',slot(64));a.call('rt.objectToPrimitiveNumber');for(const n of [0,8]){a.load('rax',slot(80+n));a.store(slot(64+n),'rax');}a.jmp(inspect);
  a.label(boolean);a.load('rax',slot(72));a.test('rax','rax');const falseValue=a.unique('falseValue');a.jcc('e',falseValue);a.lea('rax',{rip:'rt.bigint.one'});a.jmp('rt.BigInt.booleanReady');a.label(falseValue);a.lea('rax',{rip:'rt.bigint.zero'});a.label('rt.BigInt.booleanReady');a.store(slot(72),'rax');a.mov('rax',7);a.store(slot(64),'rax');a.jmp(done);
  a.label(number);a.lea('rcx',slot(80));a.lea('rdx',slot(64));a.call('rt.bigintFromDoubleInteger');for(const offset of [0,8]){a.load('rax',slot(80+offset));a.store(slot(64+offset),'rax');}a.jmp(done);
  a.label(string);a.lea('rcx',slot(80));a.load('rdx',slot(72));a.mov('r8',0);a.call('rt.bigintFromDecimal');for(const n of [0,8]){a.load('rax',slot(80+n));a.store(slot(64+n),'rax');}
  a.label(done);a.load('rcx',slot(40));for(const n of [0,8]){a.load('rax',slot(64+n));a.store({base:'rcx',disp:n},'rax');}
 });
 // RDX Value* -> RCX exact ToBigInt(value); unlike BigInt(), Numbers are rejected.
 rootedFn(b,'rt.toBigIntValue',120,[{kind:'output',register:'rcx'},{kind:'value',register:'rdx'},{kind:'locals',offset:64,count:2}],a=>{
  a.store(slot(40),'rcx');for(const n of [0,8]){a.load('rax',{base:'rdx',disp:n});a.store(slot(64+n),'rax');}
  const inspect=a.unique('inspect'),object=a.unique('object'),convert=a.unique('convert');a.label(inspect);
  a.load('rax',slot(64));a.cmp('rax',7);a.jcc('e',convert);a.cmp('rax',5);a.jcc('e',object);a.cmp('rax',4);a.jcc('e',convert);a.cmp('rax',2);a.jcc('e',convert);a.call('rt.throwTypeError');
  a.label(object);a.lea('rcx',slot(80));a.lea('rdx',slot(64));a.call('rt.objectToPrimitiveNumber');for(const n of [0,8]){a.load('rax',slot(80+n));a.store(slot(64+n),'rax');}a.jmp(inspect);
  a.label(convert);a.load('rcx',slot(40));a.mov('rdx',1);a.lea('r8',slot(64));a.call('rt.BigInt.code');
 });
 b.bundle.fragments.push(stringLiteral('rt.bigint.one','1'));
 for(const method of ['asUintN','asIntN'] as const){
  const symbol='rt.BigInt.'+method+'.fn';prependFunctionBuiltin(b,symbol,method,2,'rt.BigInt');
  rootedFn(b,symbol+'.code',184,[{kind:'output',register:'rcx'},{kind:'range',register:'r8',count:'rdx'},{kind:'locals',offset:80,count:3}],a=>{
   a.store(slot(40),'rcx');a.store(slot(48),'rdx');a.store(slot(56),'r8');a.mov('rax',0);a.store(slot(80),'rax');a.store(slot(88),'rax');a.test('rdx','rdx');const first=a.unique('first');a.jcc('e',first);for(const offset of [0,8]){a.load('rax',{base:'r8',disp:offset});a.store(slot(80+offset),'rax');}a.label(first);
   a.lea('rcx',slot(112));a.lea('rdx',slot(80));a.call('rt.toNumber');a.movsd('xmm0',slot(120));a.ucomisd('xmm0','xmm0');const nan=a.unique('nan'),bitsReady=a.unique('bitsReady');a.jcc('p',nan);a.cvttsd2si('rax','xmm0');a.cmp('rax',0);const invalid=a.unique('invalid');a.jcc('l',invalid);a.mov('r10',9007199254740991n);a.cmp('rax','r10');a.jcc('a',invalid);a.jmp(bitsReady);a.label(nan);a.mov('rax',0);a.jmp(bitsReady);a.label(invalid);a.call('rt.throwRangeError');a.label(bitsReady);a.store(slot(64),'rax');
   a.load('rax',slot(48));a.cmp('rax',2);const supplied=a.unique('supplied');a.jcc('ae',supplied);a.call('rt.throwTypeError');a.label(supplied);a.load('r10',slot(56));for(const offset of [0,8]){a.load('rax',{base:'r10',disp:16+offset});a.store(slot(96+offset),'rax');}
   const inspect=a.unique('inspect'),object=a.unique('object'),convert=a.unique('convert'),converted=a.unique('converted');a.label(inspect);a.load('rax',slot(96));a.cmp('rax',7);a.jcc('e',converted);a.cmp('rax',3);a.jcc('e','rt.throwTypeError');a.cmp('rax',5);a.jcc('e',object);a.jmp(convert);a.label(object);a.lea('rcx',slot(112));a.lea('rdx',slot(96));a.call('rt.objectToPrimitiveNumber');for(const offset of [0,8]){a.load('rax',slot(112+offset));a.store(slot(96+offset),'rax');}a.jmp(inspect);
   a.label(convert);a.lea('rcx',slot(80));a.mov('rdx',1);a.lea('r8',slot(96));a.call('rt.BigInt.code');a.jmp('rt.bigintAsN.converted.'+method);a.label(converted);for(const offset of [0,8]){a.load('rax',slot(96+offset));a.store(slot(80+offset),'rax');}a.label('rt.bigintAsN.converted.'+method);
   a.load('rcx',slot(40));a.load('rdx',slot(64));a.lea('r8',slot(80));a.mov('r9',method==='asIntN'?1:0);a.call('rt.bigintAsN');
  });
 }
 emitFunctionBuiltin(b,'rt.bigintToString.fn','toString',0,'rt.bigintPrototype.valueOf','rt.bigintPrototype');
 emitFunctionBuiltin(b,'rt.bigintValueOf.fn','valueOf',0,undefined,'rt.bigintPrototype');
 b.bundle.fragments.push(stringLiteral('rt.bigint.tag','BigInt'));
 const tag=new Uint8Array(P.size);tag[P.value]=4;tag[P.attributes]=A.configurable;
 const prototypeHead=b.bundle.fragments.find(f=>f.name==='rt.bigintPrototype')!.fixups.find(f=>f.offset===O.properties)!;
 b.bundle.fragments.push({name:'rt.bigintPrototype.@@toStringTag',section:'.data',alignment:8,bytes:tag,symbols:{},fixups:[
  {offset:P.next,kind:'va64',target:prototypeHead.target,addend:0},
  {offset:P.key,kind:'va64',target:'rt.Symbol.toStringTag.value',addend:0},
  {offset:P.value+8,kind:'va64',target:'rt.bigint.tag',addend:0},
 ]});
 prototypeHead.target='rt.bigintPrototype.@@toStringTag';
 rootedFn(b,'rt.bigintToRadix',232,[{kind:'output',register:'rcx'},{kind:'value',register:'rdx'},{kind:'locals',offset:64,count:3}],a=>{
  a.store(slot(40),'rcx');a.mov('rax',4);a.store(slot(64),'rax');a.load('rax',{base:'rdx',disp:8});a.store(slot(72),'rax');a.store(slot(112),'r8');a.load('r10',{base:'rax'});a.store(slot(128),'r10');a.mov('rax',0);a.store(slot(120),'rax');
  a.load('r10',slot(72));a.load('rax',{base:'r10',disp:8},16);const positive=a.unique('positive');a.cmp('rax',45);a.jcc('ne',positive);a.mov('rax',1);a.store(slot(120),'rax');a.label(positive);
  a.load('rax',slot(128));a.load('r10',slot(120));a.sub('rax','r10');a.store(slot(128),'rax');a.mov('rcx','rax');a.shl('rcx',1);a.add('rcx',8);a.call('rt.alloc');a.mov('r10',4);a.store(slot(80),'r10');a.store(slot(88),'rax');a.load('r10',slot(128));a.store({base:'rax'},'r10');
  a.mov('rax',0);a.store(slot(160),'rax');const copy=a.unique('copy'),copied=a.unique('copied');a.label(copy);a.load('rax',slot(160));a.load('r10',slot(128));a.cmp('rax','r10');a.jcc('ae',copied);a.load('r11',slot(120));a.add('r11','rax');a.shl('r11',1);a.load('r10',slot(72));a.add('r10','r11');a.load('r11',{base:'r10',disp:8},16);a.load('r10',slot(88));a.load('rax',slot(160));a.shl('rax',1);a.add('r10','rax');a.store({base:'r10',disp:8},'r11',16);a.load('rax',slot(160));a.add('rax',1);a.store(slot(160),'rax');a.jmp(copy);a.label(copied);
  a.load('rax',slot(128));a.shl('rax',2);a.load('r10',slot(120));a.add('rax','r10');a.add('rax',1);a.store(slot(144),'rax');a.mov('rcx','rax');a.shl('rcx',1);a.add('rcx',8);a.call('rt.alloc');a.mov('r10',4);a.store(slot(96),'r10');a.store(slot(104),'rax');a.load('r10',slot(144));a.store({base:'rax'},'r10');a.store(slot(152),'r10');
  const outer=a.unique('outer'),inner=a.unique('inner'),innerDone=a.unique('innerDone'),lower=a.unique('lower'),write=a.unique('write'),finish=a.unique('finish');a.label(outer);a.mov('rax',0);a.store(slot(160),'rax');a.store(slot(168),'rax');a.store(slot(176),'rax');a.label(inner);a.load('rax',slot(160));a.load('r10',slot(128));a.cmp('rax','r10');a.jcc('ae',innerDone);a.shl('rax',1);a.load('r10',slot(88));a.add('r10','rax');a.load('rax',{base:'r10',disp:8},16);a.sub('rax',48);a.load('r11',slot(168));a.mov('r10',10);a.imul('r11','r10');a.add('rax','r11');a.xor('rdx','rdx');a.load('r10',slot(112));a.div('r10');a.store(slot(168),'rdx');a.test('rax','rax');const zeroDigit=a.unique('zeroDigit');a.jcc('e',zeroDigit);a.mov('r11',1);a.store(slot(176),'r11');a.label(zeroDigit);a.add('rax',48);a.load('r10',slot(160));a.shl('r10',1);a.load('r11',slot(88));a.add('r11','r10');a.store({base:'r11',disp:8},'rax',16);a.load('rax',slot(160));a.add('rax',1);a.store(slot(160),'rax');a.jmp(inner);
  a.label(innerDone);a.load('rax',slot(152));a.sub('rax',1);a.store(slot(152),'rax');a.load('rax',slot(168));a.cmp('rax',10);a.jcc('ae',lower);a.add('rax',48);a.jmp(write);a.label(lower);a.add('rax',87);a.label(write);a.load('r10',slot(152));a.shl('r10',1);a.load('r11',slot(104));a.add('r11','r10');a.store({base:'r11',disp:8},'rax',16);a.load('rax',slot(176));a.test('rax','rax');a.jcc('ne',outer);
  a.load('rax',slot(120));a.test('rax','rax');a.jcc('e',finish);a.load('rax',slot(152));a.sub('rax',1);a.store(slot(152),'rax');a.shl('rax',1);a.load('r10',slot(104));a.add('r10','rax');a.mov('rax',45);a.store({base:'r10',disp:8},'rax',16);
  a.label(finish);a.lea('rcx',slot(96));a.load('rdx',slot(104));a.load('r8',slot(152));a.load('r9',slot(144));a.call('rt.jsonSlice');a.load('rcx',slot(40));a.mov('rax',7);a.store({base:'rcx'},'rax');a.load('rax',slot(104));a.store({base:'rcx',disp:8},'rax');
 });
 for(const method of ['toString','valueOf'] as const)rootedFn(b,'rt.bigint'+method[0]!.toUpperCase()+method.slice(1)+'.fn.code',168,[{kind:'output',register:'rcx'},{kind:'range',register:'r8',count:'rdx'},{kind:'locals',offset:64,count:3}],(a,frame)=>{
  a.store(slot(40),'rcx');a.store(slot(48),'rdx');a.store(slot(56),'r8');a.load('rdx',slot(frame+40));a.load('rax',{base:'rdx'});const valid=a.unique('valid');a.cmp('rax',7);a.jcc('e',valid);a.cmp('rax',5);const invalid=a.unique('invalid');a.jcc('ne',invalid);a.load('r10',{base:'rdx',disp:8});a.load('rax',{base:'r10',disp:O.kind});a.cmp('rax',BoxKind);a.jcc('ne',invalid);a.add('r10',BoxLayout.value);a.load('rax',{base:'r10'});a.cmp('rax',7);a.jcc('ne',invalid);a.mov('rdx','r10');a.jmp(valid);a.label(invalid);a.call('rt.throwTypeError');a.label(valid);
  a.mov('rax',7);a.store(slot(64),'rax');a.load('rax',{base:'rdx',disp:8});a.store(slot(72),'rax');
  if(method==='toString'){
   a.mov('r8',10);a.load('rax',slot(48));a.test('rax','rax');const decimal=a.unique('decimal');a.jcc('e',decimal);a.load('r10',slot(56));a.load('rax',{base:'r10'});a.cmp('rax',0);a.jcc('e',decimal);for(const n of [0,8]){a.load('rax',{base:'r10',disp:n});a.store(slot(80+n),'rax');}a.lea('rcx',slot(96));a.lea('rdx',slot(80));a.call('rt.toNumber');a.movsd('xmm0',slot(104));a.mov('rax',0x4000000000000000n);a.movqToXmm('xmm1','rax');a.ucomisd('xmm0','xmm1');const bad=a.unique('bad');a.jcc('p',bad);a.jcc('b',bad);a.mov('rax',0x4042800000000000n);a.movqToXmm('xmm1','rax');a.ucomisd('xmm0','xmm1');a.jcc('ae',bad);a.cvttsd2si('r8','xmm0');a.jmp(decimal);a.label(bad);a.call('rt.throwRangeError');a.label(decimal);
   a.lea('rcx',slot(96));a.lea('rdx',slot(64));a.call('rt.bigintToRadix');a.load('rcx',slot(40));a.mov('rax',4);a.store({base:'rcx'},'rax');a.load('rax',slot(104));a.store({base:'rcx',disp:8},'rax');
  }else{a.load('rcx',slot(40));a.mov('rax',7);a.store({base:'rcx'},'rax');a.load('rax',slot(72));a.store({base:'rcx',disp:8},'rax');}
 });
}
