/** Independent event and cancellation primitives; no top-level prelude bindings. */
export const eventsPreludeSource=String.raw`;(function(){
  var events=new WeakMap(), targets=new WeakMap(), signals=new WeakMap(), controllers=new WeakMap(),exceptions=new WeakMap();
  function state(map,value){var s=map.get(value);if(!s)throw new TypeError('Illegal invocation');return s}
  function domString(value){if(typeof value==='symbol')throw new TypeError('Cannot convert a Symbol value to a string');return String(value)}
  function Event(type,options){if(!new.target)throw new TypeError('Event requires new');if(arguments.length===0)throw new TypeError('Event type required');options=options||{};events.set(this,{type:domString(type),bubbles:!!options.bubbles,cancelable:!!options.cancelable,composed:!!options.composed,defaultPrevented:false,target:null,currentTarget:null,phase:0,stopped:false,immediate:false,dispatch:false,passive:false,timeStamp:performance.now()})}
  ['type','bubbles','cancelable','composed','defaultPrevented','target','currentTarget','timeStamp'].forEach(function(key){Object.defineProperty(Event.prototype,key,{enumerable:true,configurable:true,get:function(){return state(events,this)[key]}})});
  Object.defineProperties(Event.prototype,{eventPhase:{get:function(){return state(events,this).phase}},isTrusted:{get:function(){state(events,this);return false}},srcElement:{get:function(){return this.target}},cancelBubble:{get:function(){return state(events,this).stopped},set:function(v){if(v)this.stopPropagation()}},returnValue:{get:function(){return !this.defaultPrevented},set:function(v){if(!v)this.preventDefault()}}});
  Event.prototype.preventDefault=function(){var s=state(events,this);if(s.cancelable&&!s.passive)s.defaultPrevented=true};
  Event.prototype.stopPropagation=function(){state(events,this).stopped=true};
  Event.prototype.stopImmediatePropagation=function(){var s=state(events,this);s.stopped=true;s.immediate=true};
  Event.prototype.composedPath=function(){var s=state(events,this);return s.dispatch?[s.target]:[]};
  Event.prototype.initEvent=function(type,bubbles,cancelable){var s=state(events,this);if(s.dispatch)return;s.type=domString(type);s.bubbles=!!bubbles;s.cancelable=!!cancelable;s.defaultPrevented=false;s.stopped=false;s.immediate=false};
  ['NONE','CAPTURING_PHASE','AT_TARGET','BUBBLING_PHASE'].forEach(function(key,i){Object.defineProperty(Event,key,{value:i,enumerable:true});Object.defineProperty(Event.prototype,key,{value:i,enumerable:true})});
  function CustomEvent(type,options){if(!new.target)throw new TypeError('CustomEvent requires new');if(arguments.length===0){var error=new TypeError('Event type required');error.code='ERR_MISSING_ARGS';throw error}var event=Reflect.construct(Event,[type,options],new.target);state(events,event).detail=options&&options.detail!==undefined?options.detail:null;return event}
  Object.defineProperty(CustomEvent.prototype,'detail',{get:function(){return state(events,this).detail},enumerable:true,configurable:true});Object.setPrototypeOf(CustomEvent.prototype,Event.prototype);Object.setPrototypeOf(CustomEvent,Event);
  function EventTarget(){if(!new.target)throw new TypeError('EventTarget requires new');targets.set(this,{listeners:new Map(),max:api?api.defaultMaxListeners:10})}
  function capture(options){if(options!==undefined&&options!==null&&typeof options!=='boolean'&&typeof options!=='object'){var error=new TypeError('Invalid listener options');error.code='ERR_INVALID_ARG_TYPE';throw error}return typeof options==='boolean'?options:!!(options&&options.capture)}
  function add(target,type,listener,options,protectedListener,node){var s=state(targets,target);type=domString(type);if(listener==null)return;if(typeof listener!=='function'&&typeof listener!=='object')throw new TypeError('Invalid event listener');var c=capture(options),list=s.listeners.get(type)||[];if(list.some(function(x){return x.listener===listener&&x.capture===c}))return;var signal=options&&options.signal;if(signal&&state(signals,signal).aborted)return;var entry={listener:listener,capture:c,once:!!(options&&options.once),passive:!!(options&&options.passive),protected:!!protectedListener,node:!!node,removed:false,cleanup:null};list.push(entry);s.listeners.set(type,list);if(signal)entry.cleanup=protect(signal,function(){remove(target,type,listener,c)});if(s.max>0&&list.length>s.max&&!list.warned){list.warned=true;var warning=new Error('Possible EventTarget memory leak detected. '+list.length+' '+type+' listeners added.');warning.name='MaxListenersExceededWarning';warning.target=target;warning.type=type;warning.count=list.length;if(globalThis.process&&typeof globalThis.process.emitWarning==='function')globalThis.process.emitWarning(warning)}}
  function remove(target,type,listener,options){var s=state(targets,target),list=s.listeners.get(String(type));if(!list)return;var c=capture(options);for(var i=0;i<list.length;i++)if(list[i].listener===listener&&list[i].capture===c){var entry=list[i];entry.removed=true;list.splice(i,1);if(entry.cleanup)entry.cleanup();break}if(!list.length)s.listeners.delete(String(type))}
  EventTarget.prototype.addEventListener=function(type,listener,options){add(this,type,listener,options,false,false)};
  EventTarget.prototype.removeEventListener=function(type,listener,options){remove(this,type,listener,options)};
  function dispatch(target,event,arg,node){var s=state(targets,target),e=state(events,event);if(e.dispatch){var error=new Error('The event is already being dispatched');error.code='ERR_EVENT_RECURSION';throw error}var list=s.listeners.get(e.type);e.target=target;e.currentTarget=target;e.phase=2;e.dispatch=true;try{if(list)for(var entry of list.slice()){if(entry.removed||(e.immediate&&!entry.protected))continue;if(entry.once)remove(target,e.type,entry.listener,entry.capture);try{e.passive=entry.passive;var result=typeof entry.listener==='function'?entry.listener.call(target,entry.node?arg:event):(typeof entry.listener.handleEvent==='function'?entry.listener.handleEvent(event):undefined);if(result&&typeof result.then==='function')result.then(undefined,function(error){queueMicrotask(function(){throw error})})}catch(error){queueMicrotask(function(){throw error})}}}finally{e.passive=false;e.dispatch=false;e.currentTarget=null;e.phase=0}return node?!!(list&&list.length):!e.defaultPrevented}
  EventTarget.prototype.dispatchEvent=function(event){return dispatch(this,event)};
  function protect(signal,listener){state(signals,signal);add(signal,'abort',listener,{once:true},true,false);return function(){remove(signal,'abort',listener,false)}}
  function AbortSignal(){throw new TypeError('Illegal constructor')}
  Object.setPrototypeOf(AbortSignal.prototype,EventTarget.prototype);Object.setPrototypeOf(AbortSignal,EventTarget);
  function makeSignal(){var signal=Reflect.construct(EventTarget,[],AbortSignal);signals.set(signal,{aborted:false,reason:undefined,onabort:null,onabortListener:null,cleanup:[],dependents:[]});targets.get(signal).max=0;return signal}
  function markAborted(signal,reason,pending){var s=state(signals,signal);if(s.aborted)return;s.aborted=true;s.reason=reason;pending.push(signal);for(var cleanup of s.cleanup)cleanup();s.cleanup=[];for(var dependent of s.dependents.slice())if(dependent.active)markAborted(dependent.signal,reason,pending);s.dependents=[]}function abort(signal,reason){if(state(signals,signal).aborted)return;var pending=[];markAborted(signal,reason===undefined?new DOMException('This operation was aborted','AbortError'):reason,pending);for(var current of pending)current.dispatchEvent(new Event('abort'))}function depend(source,signal){var entry={active:true,signal:signal};state(signals,source).dependents.push(entry);return function(){entry.active=false;entry.signal=null}}
  Object.defineProperties(AbortSignal.prototype,{aborted:{get:function(){return state(signals,this).aborted}},reason:{get:function(){return state(signals,this).reason}},onabort:{get:function(){return state(signals,this).onabort},set:function(fn){var s=state(signals,this);s.onabort=typeof fn==='function'?fn:null;if(!s.onabortListener&&s.onabort){s.onabortListener=function(event){if(s.onabort)return s.onabort.call(this,event)};this.addEventListener('abort',s.onabortListener)}}}});
  AbortSignal.prototype.throwIfAborted=function(){var s=state(signals,this);if(s.aborted)throw s.reason};
  AbortSignal.abort=function(reason){var signal=makeSignal();abort(signal,reason);return signal};
  AbortSignal.timeout=function(delay){if(typeof delay!=='number')throw new TypeError('delay must be a number');if(!Number.isInteger(delay)||delay<0||delay>4294967295)throw new RangeError('delay out of range');var signal=makeSignal();setTimeout(function(){abort(signal,new DOMException('The operation was aborted due to timeout','TimeoutError'))},delay);return signal};
  AbortSignal.any=function(list){if(!Array.isArray(list))throw new TypeError('signals must be an array');var signal=makeSignal(),s=signals.get(signal);for(var source of list)state(signals,source);for(var source of list){if(source.aborted){abort(signal,source.reason);break}if(source===signal)continue;s.cleanup.push(depend(source,signal))}return signal};
  function AbortController(){if(!new.target)throw new TypeError('AbortController requires new');controllers.set(this,makeSignal())}
  Object.defineProperty(AbortController.prototype,'signal',{get:function(){return state(controllers,this)}});AbortController.prototype.abort=function(reason){abort(state(controllers,this),reason)};
  var exceptionNames=['IndexSizeError','DOMStringSizeError','HierarchyRequestError','WrongDocumentError','InvalidCharacterError','NoDataAllowedError','NoModificationAllowedError','NotFoundError','NotSupportedError','InUseAttributeError','InvalidStateError','SyntaxError','InvalidModificationError','NamespaceError','InvalidAccessError','ValidationError','TypeMismatchError','SecurityError','NetworkError','AbortError','URLMismatchError','QuotaExceededError','TimeoutError','InvalidNodeTypeError','DataCloneError'];
  var exceptionConstants=['INDEX_SIZE_ERR','DOMSTRING_SIZE_ERR','HIERARCHY_REQUEST_ERR','WRONG_DOCUMENT_ERR','INVALID_CHARACTER_ERR','NO_DATA_ALLOWED_ERR','NO_MODIFICATION_ALLOWED_ERR','NOT_FOUND_ERR','NOT_SUPPORTED_ERR','INUSE_ATTRIBUTE_ERR','INVALID_STATE_ERR','SYNTAX_ERR','INVALID_MODIFICATION_ERR','NAMESPACE_ERR','INVALID_ACCESS_ERR','VALIDATION_ERR','TYPE_MISMATCH_ERR','SECURITY_ERR','NETWORK_ERR','ABORT_ERR','URL_MISMATCH_ERR','QUOTA_EXCEEDED_ERR','TIMEOUT_ERR','INVALID_NODE_TYPE_ERR','DATA_CLONE_ERR'];
  function DOMException(message,name){if(!new.target)throw new TypeError('DOMException requires new');var value=Reflect.construct(Error,[message===undefined?'':domString(message)],new.target);var exceptionName=name===undefined?'Error':domString(name);exceptions.set(value,{message:value.message,name:exceptionName,code:exceptionNames.indexOf(exceptionName)+1});delete value.message;return value}Object.setPrototypeOf(DOMException.prototype,Error.prototype);
  ['message','name','code'].forEach(function(key){Object.defineProperty(DOMException.prototype,key,{get:function(){return state(exceptions,this)[key]},enumerable:true,configurable:true})});exceptionConstants.forEach(function(name,i){Object.defineProperty(DOMException,name,{value:i+1,enumerable:true});Object.defineProperty(DOMException.prototype,name,{value:i+1,enumerable:true})});
  var api={defaultMaxListeners:10,state:function(target){return state(targets,target)},add:add,remove:remove,dispatch:dispatch,protect:protect};__nonaRegexpVm.events=api;Object.defineProperty(EventTarget,Symbol.for("nona.events.internal"),{value:api});
  for(var constructor of [Event,CustomEvent,EventTarget,AbortSignal,AbortController,DOMException])Object.defineProperty(constructor.prototype,Symbol.toStringTag,{value:constructor.name,configurable:true});for(var pair of [['Event',Event],['CustomEvent',CustomEvent],['EventTarget',EventTarget],['AbortSignal',AbortSignal],['AbortController',AbortController],['DOMException',DOMException]])Object.defineProperty(globalThis,pair[0],{value:pair[1],writable:true,configurable:true});
})();`;
