import {emitStrict} from './strict.js';
import {emitErrors} from './errors.js';
import {emitExceptions} from './exceptions.js';
import {emitSuperProperties} from './super-properties.js';
import {emitLiteralAccessor} from './literal-accessor.js';
import {emitObjectIntegrity} from './object-integrity.js';
import {orderIntrinsicProperties} from './intrinsic-order.js';
import {emitObjectCollections} from './object-collections.js';
import {emitPropertyDescriptors} from './property-descriptors.js';
import {emitObjectIntrospection} from './object-introspection.js';
import {RuntimeBuilder,type RuntimeRequest,type RuntimeBundle} from './abi.js';
import {emitMemory} from './memory.js';
import {emitIo} from './io.js';
import {emitStrings} from './strings.js';
import {emitPrimitives} from './primitives.js';
import {emitNumericRuntime} from './numeric.js';
import {emitBitwise} from './bitwise.js';
import {emitObjects} from './objects.js';
import {emitObjectCoercion} from './object-coercion.js';
import {emitGc} from './gc.js';
import {emitFunctions} from './functions.js';
import {emitEnvironments} from './environments.js';
import {emitGlobals} from './globals.js';
import {emitArguments} from './arguments.js';
import {emitBoxing} from './boxing.js';
import {emitFunctionCall} from './function-call.js';
import {emitFunctionApply} from './function-apply.js';
import {emitFunctionBind} from './function-bind.js';
import {emitBoundCalls} from './function-bound-call.js';
import {emitFunctionSource} from './function-source.js';
import {emitObjectMethods} from './object-methods.js';
import {emitWrapperMethods} from './wrapper-methods.js';
import {emitRadix} from './numeric/radix.js';
import {emitBuiltinConstructors} from './builtin-constructors.js';
import {emitConsole} from './console.js';
export function emitRuntime(_request:RuntimeRequest={operations:new Set()}):RuntimeBundle {const b=new RuntimeBuilder();emitMemory(b);emitExceptions(b);emitStrings(b);emitPrimitives(b);emitBitwise(b);emitObjects(b);emitGlobals(b);emitEnvironments(b);emitFunctions(b);emitConsole(b);emitFunctionCall(b);emitFunctionApply(b);emitFunctionBind(b);emitBoundCalls(b);emitFunctionSource(b);emitObjectMethods(b);emitWrapperMethods(b);emitRadix(b);emitArguments(b);emitBoxing(b);emitErrors(b);emitBuiltinConstructors(b);emitObjectIntrospection(b);emitPropertyDescriptors(b);emitObjectCollections(b);emitLiteralAccessor(b);emitSuperProperties(b);emitObjectIntegrity(b);emitStrict(b);orderIntrinsicProperties(b);emitObjectCoercion(b);emitGc(b);emitIo(b);const n=emitNumericRuntime();b.bundle.fragments.push(...n.fragments);b.bundle.functions.push(...n.functions);return b.bundle;}
export type {RuntimeRequest,RuntimeBundle} from './abi.js';
