/** Ordered operator workers bound active calls and retained results separately. */
export const streamOperatorsSource=String.raw`
 var skipValue=Symbol('stream.skip'),Controller=AbortController,SignalConstructor=AbortSignal,numeric=Number,floor= Math.floor,ceil=Math.ceil;
 function operatorOptions(options){options=optionsOf(options);var concurrency=options.concurrency==null?1:floor(numeric(options.concurrency));if(!isInteger(concurrency)||concurrency<1)throw error(RangeError,'ERR_OUT_OF_RANGE','The concurrency must be a positive integer');var hwm=options.highWaterMark==null?concurrency*2-1:floor(numeric(options.highWaterMark));if(!isInteger(hwm)||hwm<0)throw error(RangeError,'ERR_OUT_OF_RANGE','The highWaterMark must be a nonnegative integer');checkOperatorSignal(options.signal);return {concurrency:concurrency,hwm:hwm,signal:options.signal}}
 function checkOperatorSignal(signal){if(signal!=null&&(!signal||typeof signal.addEventListener!=='function'||typeof signal.removeEventListener!=='function'))throw error(TypeError,'ERR_INVALID_ARG_TYPE','The signal must be an AbortSignal')}
 function checkFunction(fn){if(typeof fn!=='function')throw error(TypeError,'ERR_INVALID_ARG_TYPE','The callback must be a function')}
 function mapped(source,fn,options){checkFunction(fn);var config=operatorOptions(options),controller=new Controller(),signal=controller.signal;if(config.signal!=null&&!apply(defaultInstance,SignalConstructor,[config.signal]))throw error(TypeError,'ERR_INVALID_ARG_TYPE','The signal must be an AbortSignal');
  return Readable.from((async function*(){var iterator=source[asyncIteratorSymbol](),jobs=[],active=0,pulling=false,inputDone=false,stopped=false,fatal=null,wakeConsumer=null;
   function wake(){if(wakeConsumer){var resolve=wakeConsumer;wakeConsumer=null;resolve()}}
   function abort(){fatal=abortError();controller.abort(config.signal.reason);wake()}
   async function fill(){if(pulling||stopped||fatal)return;pulling=true;try{while(!stopped&&!fatal&&!inputDone&&active<config.concurrency&&jobs.length<config.concurrency+config.hwm){var step=await iterator.next();if(step.done){inputDone=true;break}if(stopped||fatal)break;var job={done:false,value:undefined,failure:null};append(jobs,job);active++;
     (function(job,value){resolvePromise(apply(fn,undefined,[value,{signal:signal}])).then(function(result){job.value=result;job.done=true;active--;fill();wake()},function(reason){job.failure=reason;job.done=true;active--;fatal=reason;wake()})})(job,step.value)
    }}catch(reason){fatal=reason}finally{pulling=false;wake();if(!stopped&&!fatal&&!inputDone&&active<config.concurrency&&jobs.length<config.concurrency+config.hwm)fill()}}
   if(config.signal){if(typeof config.signal.addEventListener!=='function')throw error(TypeError,'ERR_INVALID_ARG_TYPE','The signal must be an AbortSignal');if(config.signal.aborted)abort();else config.signal.addEventListener('abort',abort,{once:true})}
   try{fill();for(;;){if(fatal)throw fatal;if(jobs.length&&jobs[0].done){var job=shift(jobs);fill();if(job.failure)throw job.failure;if(job.value!==skipValue)yield job.value}else if(inputDone&&!jobs.length)break;else await new Promise(function(resolve){wakeConsumer=resolve})}}
   finally{stopped=true;if(config.signal)config.signal.removeEventListener('abort',abort);if(!inputDone&&typeof iterator['return']==='function')await iterator['return']()}
  })())
 }
 Readable.prototype.map=function(fn,options){return mapped(this,fn,options)};
 Readable.prototype.filter=function(fn,options){checkFunction(fn);return mapped(this,async function(value,context){return await apply(fn,undefined,[value,context])?value:skipValue},options)};
 Readable.prototype.flatMap=function(fn,options){var mappedStream=mapped(this,fn,options);return Readable.from((async function*(){for await(var values of mappedStream){var iterator=iteratorOf(values);try{for(;;){var result=await iterator.next();if(result.done)break;yield result.value}}finally{if(typeof iterator['return']==='function')await iterator['return']()}}})())};
 function limitOf(limit){limit=numeric(limit);if(limit<0)throw error(RangeError,'ERR_OUT_OF_RANGE','The limit must be nonnegative');return ceil(limit)||0}
 async function* abortableValues(source,signal,withCause,deferred){checkOperatorSignal(signal);if(!deferred&&signal&&signal.aborted)throw abortError(withCause?signal.reason:undefined);var iterator=source[asyncIteratorSymbol](),ended=false;function abort(){source.destroy(abortError(withCause?signal.reason:undefined))}if(signal)signal.addEventListener('abort',abort,{once:true});try{for(;;){var step=await iterator.next();if(step.done){ended=true;return}if(signal&&signal.aborted)throw abortError(withCause?signal.reason:undefined);yield step.value}}finally{if(signal)signal.removeEventListener('abort',abort);if(!ended&&typeof iterator['return']==='function')await iterator['return']()}}
 Readable.prototype.drop=function(limit,options){limit=limitOf(limit);var source=this;options=optionsOf(options);checkOperatorSignal(options.signal);return Readable.from((async function*(){for await(var value of abortableValues(source,options.signal,false)){if(limit)limit--;else yield value}})())};
 Readable.prototype.take=function(limit,options){limit=limitOf(limit);var source=this;options=optionsOf(options);checkOperatorSignal(options.signal);return Readable.from((async function*(){if(options.signal&&options.signal.aborted)throw abortError();if(!limit){source.destroy();return}for await(var value of abortableValues(source,options.signal,false)){yield value;if(!--limit)break}})())};
 function aggregationOptions(stream,options){options=optionsOf(options);checkOperatorSignal(options.signal);if(options.signal&&options.signal.aborted){var reason=abortError(options.signal.reason);stream.on('error',function(){});stream.destroy(reason);throw reason}return options}
 Readable.prototype.toArray=async function(options){options=optionsOf(options);checkOperatorSignal(options.signal);var values=[];for await(var value of abortableValues(this,options.signal,true,true))append(values,value);return values};
 Readable.prototype.forEach=async function(fn,options){for await(var value of mapped(this,fn,options)){} };
 Readable.prototype.some=async function(fn,options){for await(var value of mapped(this,fn,options))if(value)return true;return false};
 Readable.prototype.every=async function(fn,options){for await(var value of mapped(this,fn,options))if(!value)return false;return true};
 Readable.prototype.find=async function(fn,options){checkFunction(fn);for await(var pair of mapped(this,async function(value,context){return [value,await apply(fn,undefined,[value,context])]},options))if(pair[1])return pair[0];return undefined};
 Readable.prototype.reduce=async function(fn,initial,options){checkFunction(fn);options=aggregationOptions(this,options);var controller=new Controller(),signal=controller.signal,present=arguments.length>1,total=initial;function abort(){controller.abort(options.signal.reason)}if(options.signal)options.signal.addEventListener('abort',abort,{once:true});try{for await(var value of abortableValues(this,options.signal,true)){if(!present){total=value;present=true}else total=await apply(fn,undefined,[total,value,{signal:signal}])}if(!present)throw error(TypeError,'ERR_MISSING_ARGS','Reduce of an empty stream requires an initial value');return total}finally{if(options.signal)options.signal.removeEventListener('abort',abort);controller.abort()}};
`;
