/** Duplex factories connect independent readable demand and writable completion. */
export const streamComposeSource=String.raw`
 function duplexPair(options){options=optionsOf(options);var peers=[null,null],pending=[null,null];function make(index){var settings=copyOptions(options);settings.read=function(){var callback=pending[1-index];pending[1-index]=null;if(callback)callback()};settings.write=function(chunk,encoding,callback){var peer=peers[1-index];if(peer.destroyed){callback(error(Error,'ERR_STREAM_DESTROYED','The peer stream is destroyed'));return}if(peer.push(chunk))callback();else pending[index]=callback};settings.final=function(callback){peers[1-index].push(null);callback()};settings.destroy=function(reason,callback){var write=pending[index];pending[index]=null;if(write)write(reason||error(Error,'ERR_STREAM_DESTROYED','The stream is destroyed'));callback(reason)};return new Duplex(settings)}peers[0]=make(0);peers[1]=make(1);return peers}
 Duplex.from=function(input){var common=input&&apply(weakGet,states,[input]);if(common&&common.readable&&common.writable)return input;
  if(typeof input==='function'){var ingress=new PassThrough({objectMode:true}),controller=new Controller(),result;try{result=apply(input,undefined,[ingress,{signal:controller.signal}])}catch(reason){ingress.destroy();throw reason}if(result&&typeof result.then==='function'){var settings={objectMode:true,readable:false,write:function(chunk,encoding,callback){ingress.write(chunk,callback)},final:function(callback){ingress.end();resolvePromise(result).then(function(value){if(value!==undefined&&value!==null)callback(error(TypeError,'ERR_INVALID_RETURN_VALUE','The function must resolve to undefined or null'));else callback()},callback)},destroy:function(reason,callback){controller.abort(reason);ingress.on('error',function(){});ingress.destroy(reason);callback(reason)}};var writeOnly=new Duplex(settings);resolvePromise(result).catch(function(reason){writeOnly.destroy(reason)});return writeOnly}var transform=duplexFromPair(Readable.from(result),ingress,{objectMode:true});transform.once('close',function(){controller.abort()});return transform}
  if(common){if(common.readable)return duplexFromPair(input,new Writable({objectMode:false,write:function(chunk,encoding,callback){callback()}}),{readableObjectMode:input.readableObjectMode,writableObjectMode:false,writable:false});return duplexFromPair(Readable.from([],{objectMode:false}),input,{writableObjectMode:input.writableObjectMode,readable:false})}
  if(input&&typeof input.getReader==='function')return Duplex.from(Readable.fromWeb(input));if(input&&typeof input.getWriter==='function')return Duplex.from(Writable.fromWeb(input));
  if(input&&typeof input==='object'&&('readable' in input||'writable' in input)){var readable=input.readable,writable=input.writable;if(readable&&typeof readable.getReader==='function')readable=Readable.fromWeb(readable);if(writable&&typeof writable.getWriter==='function')writable=Writable.fromWeb(writable);return duplexFromPair(readable||Readable.from([]),writable||new Writable({objectMode:true,write:function(chunk,encoding,callback){callback()}}),{objectMode:true,readable:!!readable,writable:!!writable,readableObjectMode:!!(readable&&readable.readableObjectMode),writableObjectMode:!!(writable&&writable.writableObjectMode)})}
  if(input instanceof BlobConstructor){var blob=input;input=Readable.from((async function*(){yield await blob.arrayBuffer()})())}else if(input&&typeof input.then==='function'){var promise=input;input=Readable.from((async function*(){var value=await promise;if(value!==undefined&&value!==null)yield value})())}else input=Readable.from(input);
  return duplexFromPair(input,new Writable({objectMode:true,write:function(chunk,encoding,callback){callback()}}),{objectMode:true,writable:false})
 };
 function compose(){var streams=[];for(var i=0;i<arguments.length;i++)append(streams,Duplex.from(arguments[i]));if(!streams.length)throw error(TypeError,'ERR_MISSING_ARGS','At least one stream is required');if(streams.length===1)return streams[0];var first=streams[0],last=streams[streams.length-1],result=duplexFromPair(last,first,{readableObjectMode:last.readableObjectMode,writableObjectMode:first.writableObjectMode,readable:last.readable,writable:first.writable});var args=streams.slice();append(args,function(reason){if(reason)result.destroy(reason)});apply(pipeline,undefined,args);return result}
 Readable.prototype.compose=function(stage,options){options=optionsOf(options);var result=compose(this,stage);if(options.signal)addAbortSignal(options.signal,result);return Readable.from(result)};
 Readable.prototype.wrap=function(input){if(!input||typeof input.on!=='function')throw error(TypeError,'ERR_INVALID_ARG_TYPE','Expected a stream');var output=this;input.on('data',function(chunk){if(!output.push(chunk)&&typeof input.pause==='function')input.pause()});input.on('end',function(){output.push(null)});input.on('error',function(reason){output.destroy(reason)});input.on('close',function(){if(!readableState(output).eof)output.destroy()});output._read=function(){if(typeof input.resume==='function')input.resume()};output._destroy=function(reason,callback){if(typeof input.destroy==='function')input.destroy(reason);callback(reason)};return output};Readable.wrap=function(input,options){return new Readable(options).wrap(input)};
 if(Symbol.asyncDispose===undefined)define(Symbol,'asyncDispose',{value:Symbol.for('nodejs.asyncDispose')});
 function asyncDispose(){var stream=this;if(stream.closed)return stream.errored&&stream.errored.name!=='AbortError'?rejectPromise(stream.errored):resolvePromise();return new Promise(function(resolve,reject){stream.on('error',function(){});stream.once('close',function(){if(stream.errored&&stream.errored.name!=='AbortError')reject(stream.errored);else resolve()});stream.destroy(abortError())})}
 define(Readable.prototype,Symbol.asyncDispose,{value:asyncDispose,writable:true,configurable:true});define(Writable.prototype,Symbol.asyncDispose,{value:asyncDispose,writable:true,configurable:true});
 for(var pair of [['compose',compose],['duplexPair',duplexPair],['_isArrayBufferView',isView],['_isUint8Array',function(value){return value instanceof U8}],['_uint8ArrayToBuffer',function(value){return apply(bufferFrom,Bytes,[value.buffer,value.byteOffset,value.byteLength])}]])define(Stream,pair[0],{value:pair[1],writable:true,enumerable:true,configurable:true});
`;
