/** Adapters retain one Web reader or writer and route demand through Node queues. */
export const streamWebSource=String.raw`
 var WebReadable=ReadableStream,WebWritable=WritableStream,U8=Uint8Array,webStates=new WeakMap();
 function watchAbort(signal,callback){if(vm.events&&vm.events.isSignal(signal))return vm.events.protect(signal,callback);if(typeof EventEmitter.addAbortListener==='function'){var subscription=EventEmitter.addAbortListener(signal,callback);return function(){subscription[Symbol.dispose]()}}signal.addEventListener('abort',callback,{once:true});return function(){signal.removeEventListener('abort',callback)}}
 function webStreamStatus(value){var s=apply(weakGet,webStates,[value]);if(s)return {readable:!s.closed&&!s.failed,writable:null,errored:!!s.failed,reason:s.failure,closed:s.closed||s.failed,disturbed:s.disturbed,abortable:true};return typeof vm.bufferWebState==='function'?vm.bufferWebState(value):undefined}
 function observeWeb(value,callback){var s=apply(weakGet,webStates,[value]);if(!s)return vm.observeBufferWebStream(value,callback);var entry={active:true,callback:callback};function invoke(){if(entry.active){entry.active=false;callback(s.failure,!!s.failed)}}if(s.closed||s.failed)resolvePromise().then(invoke);else{if(!s.observers)s.observers=[];append(s.observers,entry)}return function(){entry.active=false;if(s.observers){for(var i=0;i<s.observers.length;i++)if(s.observers[i]===entry){apply(arraySplice,s.observers,[i,1]);break}if(!s.observers.length)s.observers=null}}}
 function notifyWeb(s){var list=s.observers;s.observers=null;if(list)for(var entry of list)(function(entry){resolvePromise().then(function(){if(entry.active){entry.active=false;entry.callback(s.failure,!!s.failed)}})})(entry)}
 function destroyWebStream(value,reason){var s=apply(weakGet,webStates,[value]);if(s){s.fail(reason);s.source.destroy(reason);return}if(typeof vm.destroyBufferWebStream==='function')vm.destroyBufferWebStream(value,reason)}
 function finishedWeb(value,options,callback){var called=false,subscription=null,unobserve=null;checkOperatorSignal(options.signal);function cleanup(){if(unobserve){unobserve();unobserve=null}if(subscription){subscription[Symbol.dispose]();subscription=null}}function complete(reason){if(called)return;called=true;cleanup();callback(reason)}unobserve=observeWeb(value,complete);if(options.signal){function abort(){complete(abortError(options.signal.reason))}if(options.signal.aborted)later(abort);else if(typeof EventEmitter.addAbortListener==='function')subscription=EventEmitter.addAbortListener(options.signal,abort);else{options.signal.addEventListener('abort',abort,{once:true});subscription={};subscription[Symbol.dispose]=function(){options.signal.removeEventListener('abort',abort)}}}return cleanup}
 function copyOptions(options){options=optionsOf(options);var result={};for(var key of Object.keys(options))result[key]=options[key];return result}
 function webReader(input){if(!input||typeof input.getReader!=='function')throw error(TypeError,'ERR_INVALID_ARG_TYPE','Expected a ReadableStream');return input.getReader()}
 function webWriter(input){if(!input||typeof input.getWriter!=='function')throw error(TypeError,'ERR_INVALID_ARG_TYPE','Expected a WritableStream');return input.getWriter()}
 function webValues(input){var reader=webReader(input),ended=false,iterator={next:function(){return reader.read().then(function(step){if(step.done){ended=true;reader.releaseLock()}return step})},'return':function(){if(ended)return resolvePromise({done:true,value:undefined});ended=true;return resolvePromise(reader.cancel()).then(function(){reader.releaseLock();return {done:true,value:undefined}})}};iterator[asyncIteratorSymbol]=function(){return this};return iterator}
 Readable.fromWeb=function(input,options){var reader=webReader(input),settings=copyOptions(options),busy=false,ended=false,released=false;function release(){if(!released){released=true;reader.releaseLock()}}settings.read=function(){if(busy||ended)return;busy=true;var stream=this;reader.read().then(function(step){busy=false;if(step.done){ended=true;release();stream.push(null)}else stream.push(step.value)},function(reason){busy=false;stream.destroy(reason)})};settings.destroy=function(reason,callback){if(ended){release();callback(reason);return}ended=true;resolvePromise(reader.cancel(reason)).then(function(){release();callback(reason)},function(failure){release();callback(failure)})};var result=new Readable(settings);if(settings.signal)addAbortSignal(settings.signal,result);return result};
 function readableWeb(stream,options){var nodeOptions=readableState(stream);options=optionsOf(options);var strategy=options.strategy===undefined?{}:optionsOf(options.strategy),size=strategy.size,hwm=strategy.highWaterMark===undefined?nodeOptions.hwm:numeric(strategy.highWaterMark);if(hwm!==hwm||hwm<0)throw error(RangeError,'ERR_INVALID_ARG_VALUE','The highWaterMark must be nonnegative');if(size!==undefined&&typeof size!=='function')throw error(TypeError,'ERR_INVALID_ARG_TYPE','The size must be a function');var web=create(WebReadable.prototype),s={reader:null,pending:[],queue:[],length:0,hwm:hwm,size:size,inputEnded:false,pumping:false,closed:false,cancelled:false,failed:false,failure:null,disturbed:false,source:stream,fail:null};s.fail=fail;apply(weakSet,webStates,[web,s]);
  function settle(){while(s.pending.length){var job=shift(s.pending);if(s.failed)job.reject(s.failure);else job.resolve({done:true,value:undefined})}}
  function closeIfDrained(){if(!s.inputEnded||s.queue.length||s.closed||s.failed)return;s.closed=true;if(s.reader)s.reader.resolveClosed();settle();notifyWeb(s)}
  function wake(){if(s.pumping||s.closed||s.failed||s.cancelled)return;s.pumping=true;try{for(;;){while(s.pending.length&&s.queue.length){var entry=shift(s.queue);s.length-=entry.size;shift(s.pending).resolve({done:false,value:entry.value})}closeIfDrained();if(s.closed||s.failed||s.inputEnded||(!s.pending.length&&s.length>=s.hwm))break;var nodeState=readableState(stream);if(!nodeState.queue.length)stream.read(0);if(!nodeState.queue.length)break;var count=nodeState.objectMode?1:nodeState.queue[0].length;if(!nodeState.eof&&nodeState.length-count<nodeState.hwm)callRead(stream);var chunk=consumeReadable(nodeState,count);nodeState.didRead=true;scheduleReadableWork(stream);if(nodeState.eof&&!nodeState.length)endReadable(stream);stream.emit('data',chunk);if(!nodeState.objectMode&&apply(isBuffer,Bytes,[chunk]))chunk=new U8(chunk);if(s.pending.length){shift(s.pending).resolve({done:false,value:chunk});continue}var cost=s.size===undefined?1:numeric(apply(s.size,undefined,[chunk]));if(cost!==cost||cost<0||cost===Infinity)throw error(RangeError,'ERR_INVALID_ARG_VALUE','Invalid stream chunk size');append(s.queue,{value:chunk,size:cost});s.length+=cost;}}catch(reason){fail(reason);throw reason}finally{s.pumping=false}}
  function next(owner){if(s.failed)return rejectPromise(s.failure);if(s.closed)return resolvePromise({done:true,value:undefined});return new Promise(function(resolve,reject){append(s.pending,{resolve:resolve,reject:reject,owner:owner});wake()})}
  function fail(reason){if(s.closed||s.cancelled)return;s.failed=true;s.failure=reason;s.queue=[];s.length=0;if(s.reader)s.reader.rejectClosed(reason);settle();notifyWeb(s)}
  stream.pause();apply(emitterOn,stream,['readable',wake]);stream.on('error',fail);stream.on('end',function(){s.inputEnded=true;closeIfDrained()});if(s.hwm>0)later(wake);stream.on('close',function(){if(!s.closed&&!s.cancelled&&!s.inputEnded)fail(stream.errored||prematureClose())});
  function cancel(reason){s.cancelled=true;s.closed=true;s.disturbed=true;s.queue=[];s.length=0;if(s.reader)s.reader.resolveClosed();settle();notifyWeb(s);return new Promise(function(resolve){if(stream.closed){resolve();return}stream.once('close',resolve);stream.destroy(reason===undefined?abortError():reason)})}
  function getReader(settings){settings=optionsOf(settings);if(settings.mode!==undefined)throw error(TypeError,'ERR_INVALID_ARG_VALUE','Expected a default reader');if(s.reader)throw new TypeError('ReadableStream is locked');var r={released:false,resolveClosed:null,rejectClosed:null},reader=create(ReadableStreamDefaultReader.prototype);r.closed=new Promise(function(resolve,reject){r.resolveClosed=resolve;r.rejectClosed=reject});r.closed.catch(function(){});r.reader=reader;s.reader=r;if(s.failure)r.rejectClosed(s.failure);else if(s.closed)r.resolveClosed();
   function check(){if(r.released)throw new TypeError('Reader has been released')}
   define(reader,'closed',{get:function(){return r.closed}});define(reader,'read',{value:function(){try{check();s.disturbed=true;return next(r).then(function(step){if(step.done){s.closed=true;r.resolveClosed();return step}var chunk=step.value;if(!stream.readableObjectMode&&apply(isBuffer,Bytes,[chunk]))chunk=new U8(chunk);return {done:false,value:chunk}},function(reason){if(!r.released)fail(reason);throw reason})}catch(reason){return rejectPromise(reason)}}});define(reader,'cancel',{value:function(reason){try{check();return cancel(reason)}catch(failure){return rejectPromise(failure)}}});define(reader,'releaseLock',{value:function(){if(r.released)return;r.released=true;if(s.reader===r)s.reader=null;var reason=new TypeError('Reader has been released'),retained=[];for(var job of s.pending){if(job.owner===r)job.reject(reason);else append(retained,job)}s.pending=retained;r.rejectClosed(reason);r.closed=rejectPromise(reason);r.closed.catch(function(){})}});return reader
  }
  function values(settings){var reader=getReader(),done=false,prevent=settings&&settings.preventCancel,iterator={next:function(){if(done)return resolvePromise({done:true,value:undefined});return reader.read().then(function(step){if(step.done){done=true;reader.releaseLock()}return step})},'return':function(value){if(done)return resolvePromise({done:true,value:value});done=true;return (prevent?resolvePromise():reader.cancel(value)).then(function(){reader.releaseLock();return {done:true,value:value}})}};iterator[asyncIteratorSymbol]=function(){return this};return iterator}
  async function pipeTo(destination,settings){settings=optionsOf(settings);var signal=settings.signal;checkOperatorSignal(signal);var destinationState=webStreamStatus(destination);if(!destinationState||destinationState.writable===null)throw error(TypeError,'ERR_INVALID_ARG_TYPE','Expected a WritableStream');if(s.reader||destination.locked)throw new TypeError('Stream is locked');var reader=getReader(),writer;try{writer=webWriter(destination)}catch(reason){reader.releaseLock();throw reason}var stopAbort=null,rejectAbort=null,aborted=new Promise(function(resolve,reject){rejectAbort=reject});function abort(){rejectAbort(signal.reason)}if(signal){if(signal.aborted)abort();else stopAbort=watchAbort(signal,abort)}try{for(;;){var step=await (signal?Promise.race([reader.read(),aborted]):reader.read());if(step.done)break;await writer.ready;await writer.write(step.value)}if(!settings.preventClose)await writer.close()}catch(reason){var tasks=[];if(!settings.preventAbort)append(tasks,writer.abort(reason));if(!settings.preventCancel)append(tasks,reader.cancel(reason));await Promise.all(tasks);throw reason}finally{if(stopAbort)stopAbort();reader.releaseLock();writer.releaseLock()}}
  function tee(){var iterator=values(),queues=[[],[]],waiters=[[],[]],cancelled=[false,false],ended=false,failure=null,busy=false;
   async function pull(){if(busy||ended)return;busy=true;try{var step=await iterator.next();ended=step.done;if(!step.done)for(var i=0;i<2;i++)if(!cancelled[i])append(queues[i],step.value)}catch(reason){failure=reason;ended=true}finally{busy=false;for(var i=0;i<2;i++)while(waiters[i].length)shift(waiters[i])();}}
   return [0,1].map(function(index){var input={next:async function(){while(!queues[index].length&&!ended){pull();await new Promise(function(resolve){append(waiters[index],resolve)})}if(failure)throw failure;return queues[index].length?{done:false,value:shift(queues[index])}:{done:true,value:undefined}},'return':async function(){cancelled[index]=true;if(cancelled[1-index])await iterator['return']();return {done:true,value:undefined}}};input[asyncIteratorSymbol]=function(){return this};return readableWeb(Readable.from(input,{objectMode:stream.readableObjectMode}))})
  }
  define(web,'locked',{get:function(){return s.reader!==null}});for(var pair of [['getReader',getReader],['cancel',function(reason){return s.reader?rejectPromise(new TypeError('ReadableStream is locked')):cancel(reason)}],['values',values],[asyncIteratorSymbol,values],['tee',tee],['pipeTo',pipeTo],['pipeThrough',function(pair,settings){if(!pair||!pair.readable||!pair.writable)throw new TypeError('Expected a transform pair');pipeTo(pair.writable,settings).catch(function(){});return pair.readable}]])define(web,pair[0],{value:pair[1],writable:true,configurable:true});return web
 }
 Readable.toWeb=readableWeb;
 Writable.toWeb=function(stream){writableState(stream);return new WebWritable({write:function(chunk){return new Promise(function(resolve,reject){stream.write(chunk,function(reason){if(reason)reject(reason);else resolve()})})},close:function(){return new Promise(function(resolve,reject){stream.end(function(reason){if(reason)reject(reason);else resolve()})})},abort:function(reason){return new Promise(function(resolve){if(stream.closed){resolve();return}stream.on('error',function(){});stream.once('close',resolve);stream.destroy(reason)})}})};
 function writableFromWeb(input,options){var writer=webWriter(input),settings=copyOptions(options),closed=false;settings.write=function(chunk,encoding,callback){resolvePromise(writer.ready).then(function(){return writer.write(chunk)}).then(function(){callback()},callback)};settings.final=function(callback){writer.close().then(function(){closed=true;writer.releaseLock();callback()},callback)};settings.destroy=function(reason,callback){if(closed){callback(reason);return}closed=true;writer.abort(reason).then(function(){writer.releaseLock();callback(reason)},function(failure){writer.releaseLock();callback(failure)})};var result=new Writable(settings);if(settings.signal)addAbortSignal(settings.signal,result);return result}
 Writable.fromWeb=writableFromWeb;
 Duplex.toWeb=function(stream){return {readable:Readable.toWeb(stream),writable:Writable.toWeb(stream)}};
 Duplex.fromWeb=function(pair,options){if(!pair||!pair.readable||!pair.writable)throw error(TypeError,'ERR_INVALID_ARG_TYPE','Expected a readable/writable pair');return duplexFromPair(Readable.fromWeb(pair.readable,options),Writable.fromWeb(pair.writable,options),options)};
 function duplexFromPair(input,output,options){var settings=copyOptions(options),busy=false,iterator=input.iterator({destroyOnReturn:false});settings.read=function(){if(busy)return;busy=true;var stream=this;(async function(){try{while(!stream.destroyed){var step=await iterator.next();if(step.done){stream.push(null);break}if(!stream.push(step.value))break}}catch(reason){stream.destroy(reason)}finally{busy=false}})()};settings.write=function(chunk,encoding,callback){output.write(chunk,encoding,callback)};settings.final=function(callback){output.end(callback)};settings.destroy=function(reason,callback){input.on('error',function(){});output.on('error',function(){});input.destroy(reason);output.destroy(reason);callback(reason)};var result=new Duplex(settings);input.on('error',function(reason){result.destroy(reason)});output.on('error',function(reason){result.destroy(reason)});return result}
`;
