import test from 'node:test';
import assert from 'node:assert/strict';
import {Assembler} from '../src/backend/x64/assembler.js';
import {linkHost} from './helpers/program.js';
import type {NativeProgram} from '../src/backend/pe/model.js';
import {RuntimeBuilder} from '../src/runtime/abi.js';
import {ContextLayout,emitContextSwitch} from '../src/runtime/context-switch.js';
import {runNative} from './helpers/native.js';

test('native context switch resumes both stacks with roots, handlers and nonvolatile registers',()=>{
 const b=new RuntimeBuilder();emitContextSwitch(b);
 for(const name of ['rt.gcRoots','rt.exceptionHandler','rt.cleanupHead'])b.data(name,new Uint8Array(8),'.data');
 for(const name of ['main.context','fiber.context'])b.data(name,new Uint8Array(ContextLayout.size),'.data');
 b.bundle.fragments.push({name:'fiber.stack',section:'.data',alignment:16,bytes:new Uint8Array(65536),fixups:[],symbols:{}});
 b.data('xmm.check',new Uint8Array(16),'.data');
 const entry=new Assembler('entry');entry.sub('rsp',40);
 entry.lea('r10',{rip:'fiber.stack'});entry.add('r10',65536-56);
 entry.lea('rax',{rip:'fiber.start'});entry.store({base:'r10',disp:40},'rax');
 entry.lea('rax',{rip:'fiber.context'});entry.store({base:'rax',disp:ContextLayout.stack},'r10');
 entry.mov('r10',77);entry.store({base:'rax',disp:ContextLayout.gp+4*8},'r10');
 entry.mov('r10',222);entry.store({base:'rax',disp:ContextLayout.roots},'r10');
 entry.mov('r10',666);entry.store({base:'rax',disp:ContextLayout.handler},'r10');
 entry.mov('r10',777);entry.store({base:'rax',disp:ContextLayout.cleanup},'r10');
 entry.lea('r10',{rip:'main.context'});entry.store({base:'rax',disp:ContextLayout.parent},'r10');
 entry.mov('r10',5555);entry.store({base:'rax',disp:ContextLayout.generator},'r10');
 entry.mov('r10',5678);entry.store({base:'rax',disp:ContextLayout.xmm},'r10');
 entry.mov('r10',6789);entry.store({base:'rax',disp:ContextLayout.xmm+8},'r10');
 entry.mov('r10',42);entry.mov('r12','r10');
 entry.lea('r10',{rip:'xmm.check'});entry.mov('rax',1234);entry.store({base:'r10'},'rax');entry.mov('rax',2345);entry.store({base:'r10',disp:8},'rax');entry.loadXmm128('xmm6',{base:'r10'});
 entry.mov('r10',111);entry.store({rip:'rt.gcRoots'},'r10');
 entry.mov('r10',444);entry.store({rip:'rt.exceptionHandler'},'r10');
 entry.mov('r10',555);entry.store({rip:'rt.cleanupHead'},'r10');
 entry.mov('r10',4444);entry.store({rip:'rt.currentGenerator'},'r10');
 entry.lea('rcx',{rip:'main.context'});entry.lea('rdx',{rip:'fiber.context'});entry.call('rt.switchContext');
 entry.cmp('r12',42);entry.jcc('ne','entry.bad');
 entry.load('r10',{rip:'rt.gcRoots'});entry.cmp('r10',111);entry.jcc('ne','entry.bad');
 entry.load('r10',{rip:'rt.exceptionHandler'});entry.cmp('r10',444);entry.jcc('ne','entry.bad');
 entry.load('r10',{rip:'rt.cleanupHead'});entry.cmp('r10',555);entry.jcc('ne','entry.bad');
 entry.load('r10',{rip:'rt.contextChain'});entry.test('r10','r10');entry.jcc('ne','entry.bad');
 entry.load('r10',{rip:'rt.currentGenerator'});entry.cmp('r10',4444);entry.jcc('ne','entry.bad');
 entry.lea('r10',{rip:'xmm.check'});entry.storeXmm128({base:'r10'},'xmm6');entry.load('rax',{base:'r10'});entry.cmp('rax',1234);entry.jcc('ne','entry.bad');entry.load('rax',{base:'r10',disp:8});entry.cmp('rax',2345);entry.jcc('ne','entry.bad');
 entry.lea('rcx',{rip:'main.context'});entry.lea('rdx',{rip:'fiber.context'});entry.call('rt.switchContext');
 entry.cmp('r12',42);entry.jcc('ne','entry.bad');
 entry.load('r10',{rip:'rt.gcRoots'});entry.cmp('r10',111);entry.jcc('ne','entry.bad');
 entry.mov('rcx',0);entry.callImport('ExitProcess');
 entry.label('entry.bad');entry.mov('rcx',1);entry.callImport('ExitProcess');
 entry.label('entry.end');
 const fiber=new Assembler('fiber.start');fiber.sub('rsp',40);
 fiber.cmp('r12',77);fiber.jcc('ne','fiber.bad');
 fiber.load('r10',{rip:'rt.gcRoots'});fiber.cmp('r10',222);fiber.jcc('ne','fiber.bad');
 fiber.load('r10',{rip:'rt.exceptionHandler'});fiber.cmp('r10',666);fiber.jcc('ne','fiber.bad');
 fiber.load('r10',{rip:'rt.cleanupHead'});fiber.cmp('r10',777);fiber.jcc('ne','fiber.bad');
 fiber.load('r10',{rip:'rt.contextChain'});fiber.lea('rax',{rip:'main.context'});fiber.cmp('r10','rax');fiber.jcc('ne','fiber.bad');
 fiber.load('r10',{rip:'rt.currentGenerator'});fiber.cmp('r10',5555);fiber.jcc('ne','fiber.bad');
 fiber.lea('r10',{rip:'xmm.check'});fiber.storeXmm128({base:'r10'},'xmm6');fiber.load('rax',{base:'r10'});fiber.cmp('rax',5678);fiber.jcc('ne','fiber.bad');fiber.load('rax',{base:'r10',disp:8});fiber.cmp('rax',6789);fiber.jcc('ne','fiber.bad');
 fiber.mov('r10',88);fiber.mov('r12','r10');
 fiber.lea('r10',{rip:'xmm.check'});fiber.mov('rax',7890);fiber.store({base:'r10'},'rax');fiber.mov('rax',8901);fiber.store({base:'r10',disp:8},'rax');fiber.loadXmm128('xmm6',{base:'r10'});
 fiber.mov('r10',333);fiber.store({rip:'rt.gcRoots'},'r10');
 fiber.mov('r10',888);fiber.store({rip:'rt.exceptionHandler'},'r10');
 fiber.mov('r10',999);fiber.store({rip:'rt.cleanupHead'},'r10');
 fiber.lea('rcx',{rip:'fiber.context'});fiber.lea('rdx',{rip:'main.context'});fiber.call('rt.switchContext');
 fiber.cmp('r12',88);fiber.jcc('ne','fiber.bad');
 fiber.load('r10',{rip:'rt.gcRoots'});fiber.cmp('r10',333);fiber.jcc('ne','fiber.bad');
 fiber.load('r10',{rip:'rt.exceptionHandler'});fiber.cmp('r10',888);fiber.jcc('ne','fiber.bad');
 fiber.load('r10',{rip:'rt.cleanupHead'});fiber.cmp('r10',999);fiber.jcc('ne','fiber.bad');
 fiber.load('r10',{rip:'rt.contextChain'});fiber.lea('rax',{rip:'main.context'});fiber.cmp('r10','rax');fiber.jcc('ne','fiber.bad');
 fiber.load('r10',{rip:'rt.currentGenerator'});fiber.cmp('r10',5555);fiber.jcc('ne','fiber.bad');
 fiber.lea('r10',{rip:'xmm.check'});fiber.storeXmm128({base:'r10'},'xmm6');fiber.load('rax',{base:'r10'});fiber.cmp('rax',7890);fiber.jcc('ne','fiber.bad');fiber.load('rax',{base:'r10',disp:8});fiber.cmp('rax',8901);fiber.jcc('ne','fiber.bad');
 fiber.lea('rcx',{rip:'fiber.context'});fiber.lea('rdx',{rip:'main.context'});fiber.call('rt.switchContext');
 fiber.label('fiber.bad');fiber.mov('rcx',2);fiber.callImport('ExitProcess');fiber.label('fiber.end');
 const program:NativeProgram={...b.bundle,fragments:[...b.bundle.fragments,{...entry.finish(),name:'entry',section:'.text'},{...fiber.finish(),name:'fiber.start',section:'.text'}],imports:[{dll:'KERNEL32.dll',name:'ExitProcess',symbol:'ExitProcess'}],entry:'entry',functions:[...b.bundle.functions,{begin:'entry',end:'entry.end',prologSize:4,stackAllocation:40,savedRegisters:[]},{begin:'fiber.start',end:'fiber.end',prologSize:4,stackAllocation:40,savedRegisters:[]}]};
 const run=runNative(linkHost(program));assert.equal(run.error,undefined);assert.equal(run.status,0,String(run.stderr));
});
