import {test} from 'node:test';
import {expectProgram} from './helpers/program.js';

test('JSON intrinsic metadata',()=>expectProgram(`console.log(Object.prototype.toString.call(JSON),typeof JSON.parse,JSON.parse.length,typeof JSON.stringify,JSON.stringify.length,Object.getPrototypeOf(JSON)===Object.prototype)`,'[object JSON] function 2 function 3 true\n'));
test('JSON.parse exact primitive literals',()=>expectProgram(`let errors=[];for(let s of ['null','true','false','other']){try{let v=JSON.parse(s);console.log(typeof v,String(v))}catch(e){console.log(e.name)}}`,'object null\nboolean true\nboolean false\nSyntaxError\n'));
test('JSON.parse number grammar',()=>expectProgram(`for(let s of ['0','-0','12','-12.5','1e3','1E-3','01','+1','1.','1e','1e+','NaN','Infinity']){try{let x=JSON.parse(s);console.log(s,Object.is(x,-0)?'-0':String(x))}catch(e){console.log(s,e.name)}}`,'0 0\n-0 -0\n12 12\n-12.5 -12.5\n1e3 1000\n1E-3 0.001\n01 SyntaxError\n+1 SyntaxError\n1. SyntaxError\n1e SyntaxError\n1e+ SyntaxError\nNaN SyntaxError\nInfinity SyntaxError\n'));
test('JSON.parse trims JSON whitespace only',()=>{const inputs=[' \t\ntrue\r ','\t -12.5 \n','\u000btrue',' true\u00a0'];expectProgram(`for(let s of ${JSON.stringify(inputs)}){try{console.log(JSON.parse(s))}catch(e){console.log(e.name)}}`,'true\n-12.5\nSyntaxError\nSyntaxError\n');});
test('JSON.parse quoted strings and escapes',()=>{const inputs=['"a\\n\\u0041\\/\\"\\\\z"','"\\uD800"','""','"bad\nline"','"\\x"','"unterminated'];expectProgram(`for(let s of ${JSON.stringify(inputs)}){try{let v=JSON.parse(s);console.log(JSON.stringify(v))}catch(e){console.log(e.name)}}`,'"a\\nA/\\"\\\\z"\n"\\ud800"\n""\nSyntaxError\nSyntaxError\nSyntaxError\n');});
test('JSON.stringify primitive values',()=>expectProgram(`for(let x of [null,true,false,0,-0,12.5,NaN,Infinity,-Infinity,undefined,Symbol('x')])console.log(JSON.stringify(x))`,'null\ntrue\nfalse\n0\n0\n12.5\nnull\nnull\nnull\nundefined\nundefined\n'));
test('JSON.stringify quotes controls and surrogates',()=>{const value='a"\\\n\t\u0000\ud800\udc00\ud800x';expectProgram(`console.log(JSON.stringify(${JSON.stringify(value)}))`,JSON.stringify(value)+'\n');});
