import {test} from 'node:test';
import {expectProgram} from './helpers/program.js';

test('JSON intrinsic metadata',()=>expectProgram(`console.log(Object.prototype.toString.call(JSON),typeof JSON.parse,JSON.parse.length,typeof JSON.stringify,JSON.stringify.length,Object.getPrototypeOf(JSON)===Object.prototype)`,'[object JSON] function 2 function 3 true\n'));
test('JSON.parse exact primitive literals',()=>expectProgram(`let errors=[];for(let s of ['null','true','false','other']){try{let v=JSON.parse(s);console.log(typeof v,String(v))}catch(e){console.log(e.name)}}`,'object null\nboolean true\nboolean false\nSyntaxError\n'));
test('JSON.parse number grammar',()=>expectProgram(`for(let s of ['0','-0','12','-12.5','1e3','1E-3','01','+1','1.','1e','1e+','NaN','Infinity']){try{let x=JSON.parse(s);console.log(s,Object.is(x,-0)?'-0':String(x))}catch(e){console.log(s,e.name)}}`,'0 0\n-0 -0\n12 12\n-12.5 -12.5\n1e3 1000\n1E-3 0.001\n01 SyntaxError\n+1 SyntaxError\n1. SyntaxError\n1e SyntaxError\n1e+ SyntaxError\nNaN SyntaxError\nInfinity SyntaxError\n'));
test('JSON.parse trims JSON whitespace only',()=>{const inputs=[' \t\ntrue\r ','\t -12.5 \n','\u000btrue',' true\u00a0'];expectProgram(`for(let s of ${JSON.stringify(inputs)}){try{console.log(JSON.parse(s))}catch(e){console.log(e.name)}}`,'true\n-12.5\nSyntaxError\nSyntaxError\n');});
test('JSON.parse quoted strings and escapes',()=>{const inputs=['"a\\n\\u0041\\/\\"\\\\z"','"\\uD800"','""','"bad\nline"','"\\x"','"unterminated'];expectProgram(`for(let s of ${JSON.stringify(inputs)}){try{let v=JSON.parse(s);console.log(JSON.stringify(v))}catch(e){console.log(e.name)}}`,'"a\\nA/\\"\\\\z"\n"\\ud800"\n""\nSyntaxError\nSyntaxError\nSyntaxError\n');});
test('JSON.parse nested arrays and objects',()=>{const value=' { "property" : {}, "prop2" : [true,null,123.456,{"x":[1,2]}] } ';expectProgram(`let x=JSON.parse(${JSON.stringify(value)});console.log(Object.keys(x).join(','),Object.keys(x.property).length,x.prop2.length,x.prop2[0],x.prop2[1],x.prop2[2],x.prop2[3].x[1])`,'property,prop2 0 4 true null 123.456 2\n');});
test('JSON.parse allows whitespace before every structural token',()=>{const values=['{}','{ \n }','{"property" : { }}','{ \n "property" : { } , "prop2" : [ true , null , 123.456 ] }'];expectProgram(`for(let s of ${JSON.stringify(values)}){try{JSON.parse(s);console.log('ok')}catch(e){console.log(e.name)}}`,'ok\nok\nok\nok\n');});
test('JSON.parse defines __proto__ as data and rejects trailing commas',()=>{const inputs=['{"__proto__":[],"__proto__":2}','[1,]','{"x":1,}','[1,,2]'];expectProgram(`let a=JSON.parse(${JSON.stringify(inputs[0])});console.log(Object.getPrototypeOf(a)===Object.prototype,a.__proto__);for(let s of ${JSON.stringify(inputs.slice(1))}){try{JSON.parse(s);console.log('accepted')}catch(e){console.log(e.name)}}`,'true 2\nSyntaxError\nSyntaxError\nSyntaxError\n');});
test('JSON.parse reviver visits children then root',()=>expectProgram(`let log=[];let x=JSON.parse('{"b":[1,2],"a":3}',function(k,v){log.push(k);return v});console.log(log.length,'['+log.join('|')+']',x.b[1],x.a)`,'5 [0|1|b|a|] 2 3\n'));
test('JSON.parse reviver deletes properties and owns root wrapper',()=>expectProgram(`let holder;let x=JSON.parse('{"a":1,"b":2}',function(k,v){if(k===''){holder=this}if(k==='a')return undefined;return v});console.log(Object.keys(x).join(','),Object.getPrototypeOf(holder)===Object.prototype,Object.keys(holder).join(','))`,'b true \n'));
test('JSON.parse reviver ignores failed ordinary delete and define',()=>expectProgram(`let a=JSON.parse('[1,2]',function(k,v){if(k==='0')Object.defineProperty(this,'1',{configurable:false});if(k==='1')return 22;return v});let o=JSON.parse('{"a":1,"b":2}',function(k,v){if(k==='a')Object.defineProperty(this,'b',{configurable:false});if(k==='b')return undefined;return v});console.log(a[0],a[1],o.a,o.b)`,'1 2 1 2\n'));
test('JSON.stringify primitive values',()=>expectProgram(`for(let x of [null,true,false,0,-0,12.5,NaN,Infinity,-Infinity,undefined,Symbol('x')])console.log(JSON.stringify(x))`,'null\ntrue\nfalse\n0\n0\n12.5\nnull\nnull\nnull\nundefined\nundefined\n'));
test('JSON.stringify quotes controls and surrogates',()=>{const value='a"\\\n\t\u0000\ud800\udc00\ud800x';expectProgram(`console.log(JSON.stringify(${JSON.stringify(value)}))`,JSON.stringify(value)+'\n');});
test('JSON.stringify nested arrays and objects',()=>expectProgram(`console.log(JSON.stringify([1,undefined,null,{a:true}]));console.log(JSON.stringify({a:1,b:undefined,c:[2]}))`,'[1,null,null,{"a":true}]\n{"a":1,"c":[2]}\n'));
test('JSON.stringify detects cycles and clears guard after a throw',()=>expectProgram(`let a=[];a.push(a);try{JSON.stringify(a)}catch(e){console.log(e.name)}a.pop();console.log(JSON.stringify(a))`,'TypeError\n[]\n'));
test('JSON.stringify invokes toJSON with each property key',()=>expectProgram(`let o={a:{toJSON:function(k){return k+'!'}},b:[{toJSON:function(k){return k+'?'}}]};console.log(JSON.stringify(o));console.log(JSON.stringify({toJSON:function(k){return k+'root'}}))`,'{"a":"a!","b":["0?"]}\n"root"\n'));
test('JSON.stringify unwraps primitive wrapper objects',()=>expectProgram(`console.log(JSON.stringify([new Boolean(true),new Number(2),new String('a')]));console.log(JSON.stringify({b:new Boolean(false),n:new Number(3),s:new String('x')}))`,'[true,2,"a"]\n{"b":false,"n":3,"s":"x"}\n'));
test('JSON.stringify invokes BigInt toJSON before the replacer',()=>expectProgram(`
  BigInt.prototype.toJSON=function(key){'use strict';console.log(typeof this,key);return 'converted'};
  console.log(JSON.stringify({n:1n}));
  delete BigInt.prototype.toJSON;
  try{JSON.stringify(Object(2n))}catch(error){console.log(error.name)}
  try{JSON.stringify(3n,function(key,value){return value})}catch(error){console.log(error.name)}
`,'bigint n\n{"n":"converted"}\nTypeError\nTypeError\n'));
test('JSON.stringify replacer function receives holder and key',()=>expectProgram(`let a={x:1,y:2};console.log(JSON.stringify(a,function(k,v){if(k==='x')return v+5;if(k==='y')return undefined;return v}));console.log(JSON.stringify([1,2],function(k,v){if(k==='1')return undefined;return v}))`,'{"x":6}\n[1,null]\n'));
test('JSON.stringify replacer array controls object keys recursively',()=>expectProgram(`let a={a:{b:2,c:3},b:1,c:4};console.log(JSON.stringify(a,['c','b','a','b']));console.log(JSON.stringify({a:1},[]))`,'{"c":4,"b":1,"a":{"c":3,"b":2}}\n{}\n'));
test('JSON.stringify space indents nested arrays and objects',()=>expectProgram(`console.log(JSON.stringify({a:[1,{b:2}]},null,'  '));console.log(JSON.stringify([1,2],null,1))`,'{\n  "a": [\n    1,\n    {\n      "b": 2\n    }\n  ]\n}\n[\n 1,\n 2\n]\n'));
