const SCALE = Number(process.env.SCALE) || 1; const S = n => Math.round(n * SCALE);
const N = S(1000000);
let t = performance.now();
const a = [];
for (let i = 0; i < N; i++) a.push(i);
const tPush = performance.now() - t;
t = performance.now();
const b = Array.from({ length: N }, (_, i) => i);
const tFrom = performance.now() - t;
t = performance.now();
const c = new Array(N);
for (let i = 0; i < N; i++) c[i] = i;
const tPre = performance.now() - t;
t = performance.now();
let s = 0;
for (let i = 0; i < N; i++) s += a[i];
const tFor = performance.now() - t;
t = performance.now();
const r = a.map(x => x * 2).filter(x => x % 3 === 0).reduce((acc, x) => acc + x, 0);
const tMFR = performance.now() - t;
t = performance.now();
const d = new Array(N);
let seed = 12345;
for (let i = 0; i < N; i++) { seed = (seed * 1103515245 + 12345) % 2147483648; d[i] = seed; }
d.sort((x, y) => x - y);
const tSort = performance.now() - t;
console.log(JSON.stringify({ push: tPush, from: tFrom, prealloc: tPre, forsum: tFor, mfr: tMFR, sort: tSort, check: s + r + d[0] + b[N-1] + c[N-1] }));
