import { spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = dirname(dirname(fileURLToPath(import.meta.url)));
// Keep both the Node compiler and browser compiler on the same package version.
// The emitted module is a literal, so neither target needs a runtime JSON loader.
const packageMetadata=JSON.parse(readFileSync(join(projectRoot,'package.json'),'utf8'));
if(typeof packageMetadata.version!=='string'||!packageMetadata.version)throw new Error('Package version must be a nonempty string');
const versionSource='/** Generated by scripts/build.mjs from package.json; do not edit manually. */\nexport const nonaVersion='+JSON.stringify(packageMetadata.version)+';\n';
const versionFile=join(projectRoot,'src','version.ts');
let existingVersion;try{existingVersion=readFileSync(versionFile,'utf8')}catch{}
if(existingVersion!==versionSource)writeFileSync(versionFile,versionSource,'utf8');
const compiler = join(projectRoot, 'node_modules', 'typescript', 'bin', 'tsc');
const result = spawnSync(process.execPath, [compiler, '-p', 'tsconfig.json'], {
  cwd: projectRoot,
  stdio: 'inherit',
});

if (result.error) {
  throw result.error;
}

if (result.status !== 0) {
  process.exit(result.status ?? 1);
}

const outputDirectory = join(projectRoot, 'dist');
mkdirSync(outputDirectory, { recursive: true });
writeFileSync(join(outputDirectory, 'cli.js'), "import './src/cli.js';\n", 'utf8');
