import {runOracle} from './oracle.js';
const cases=[
  `var b=Buffer.from('hé😀');console.log(b instanceof Uint8Array,Buffer.isBuffer(b),b.toString(),b.toString('hex'),Buffer.byteLength('hé😀'));var s=b.slice(1,3);s[0]=65;console.log(b[1],s.buffer===b.buffer,s instanceof Buffer);console.log(Buffer.from({type:'Buffer',data:[257,-1]}).toString('hex'));`,
  `for(var e of ['utf8','utf16le','latin1','ascii','base64','base64url','hex']){var s=e==='hex'?'deadbeef':e==='base64'||e==='base64url'?'aGVsbG8_':'Aé😀';var b=Buffer.from(s,e);console.log(e,b.toString('hex'),b.toString(e))}console.log(Buffer.isEncoding('UTF-8'),Buffer.isEncoding('no'),Buffer.byteLength(new Uint16Array(3)));`,
  `var b=Buffer.alloc(12,'ab');console.log(b.toString(),b.indexOf('ba'),b.lastIndexOf('ba'),b.includes('zz'));console.log(b.copy(b,2,0,8),b.toString());console.log(Buffer.concat([Buffer.from([1,2]),new Uint8Array([3])],5).toString('hex'));console.log(Buffer.compare(Buffer.from([1]),Buffer.from([2])),b.equals(Buffer.from(b)));console.log(JSON.stringify(b.toJSON()));`,
  `var b=Buffer.alloc(32);console.log(b.writeUIntLE(0x123456,1,3),b.readUIntBE(1,3),b.writeIntBE(-123456,4,3),b.readIntBE(4,3));b.writeDoubleLE(Math.PI,8);b.writeFloatBE(1.5,16);b.writeBigInt64BE(-123456789012345n,20);console.log(b.readDoubleLE(8),b.readFloatBE(16),b.readBigInt64BE(20));console.log(Buffer.from([1,2,3,4]).swap16().toString('hex'));`,
  `var b=Buffer.alloc(5);console.log(b.write('😀a',0,3),b.toString('hex'));console.log(b.write('😀a',0,5),b.toString());for(var f of [function(){Buffer.alloc(-1)},function(){Buffer.from(5)},function(){Buffer.from('a','bad')},function(){b.readUInt32LE(2)},function(){b.writeUInt8(256)}]){try{f()}catch(e){console.log(e.name,e.code)}}`,
  `var a=new ArrayBuffer(8),v=new Uint8Array(a);v.set([1,2,3,4]);var b=Buffer.from(a,1,3);b[0]=9;var c=Buffer.from(b);c[0]=7;console.log(v[1],b[0],c[0],b.buffer===a,Buffer.isBuffer(v));console.log(Buffer.copyBytesFrom(new Uint16Array([0x1234,0xabcd]),1,1).toString('hex'));console.log(Buffer.alloc(2.9).length,Buffer.allocUnsafeSlow(2).length,Buffer.poolSize);`,
  `var b=Buffer.from('abcabc');for(var p of [undefined,-99,-2,0,1,3,99,NaN])console.log(b.indexOf('bc',p,5),b.lastIndexOf('bc',p,5),b.indexOf('',p,5));var u=Buffer.from('abcabc','utf16le');console.log(u.indexOf('bc',1,'utf16le'),u.lastIndexOf('bc',undefined,'utf16le'));console.log(Buffer.prototype.toString.call(new Uint8Array([65,66])),Buffer.prototype.readUInt16BE.call(new Uint8Array([1,2])));`,
  `for(var e of ['utf8','utf16le','latin1','ascii','hex','base64','base64url']){var b=Buffer.alloc(8);console.log(e,b.write(e==='hex'?'4142zz':e==='base64'||e==='base64url'?'QUL/':'é😀',1,5,e),b.toString('hex'))}for(var s of ['','A','Zg==','Zg=',' Zg== ','YWJj-_/','0g','1x','ab9'])console.log(s,Buffer.from(s,'base64').toString('hex'),Buffer.from(s,'hex').toString('hex'));`,
  `var b=Buffer.alloc(12);for(var n of [1,2,3,4,5,6]){b.writeUIntLE(Math.pow(2,8*n)-1,0,n);console.log(n,b.readUIntLE(0,n),b.readUIntBE(0,n));b.writeIntBE(-Math.pow(2,8*n-1),0,n);console.log(b.readIntBE(0,n))}b.writeBigUint64LE((1n<<64n)-1n);console.log(b.readBigUint64LE(),b.readBigInt64LE());b.writeFloatLE(-0);console.log(Object.is(b.readFloatLE(),-0));`,
  `var b=Buffer.alloc(8);for(var f of [function(){b.readUIntLE(undefined,2)},function(){b.readUInt8('0')},function(){b.writeIntLE(128,0,1)},function(){b.fill('zz','hex')},function(){Buffer.alloc(NaN)},function(){Buffer.allocUnsafe(4,3)},function(){Buffer.from('x').swap16()},function(){Buffer.from('x').toString(null)}])try{f()}catch(e){console.log(e.name,e.code)}console.log(Buffer.from('ab').compare(Buffer.from('abcd'),0,2),b.copy(Buffer.alloc(0)),Buffer.from([128,255]).toString('ascii'));`,
  `var b=new Blob(['a',new Uint8Array([98,99]),new Blob(['dé'])],{type:'TEXT/PLAIN'});console.log(b.size,b.type,b instanceof Blob,Object.prototype.toString.call(b));console.log(b.slice(-3).size,b.slice(1,3,'ABC').type);var f=new File(['a'],'hé😀',{type:'TEXT/PLAIN',lastModified:123});console.log(f.name,f.lastModified,f.size,f.type,f instanceof Blob,f instanceof File,Object.prototype.toString.call(f));var a=new Uint8Array([1,2]),q=new Blob([a]);a[0]=9;console.log(q.size);`,
  `var b=Buffer.from('abc');console.log(Buffer.concat([],NaN).length,b.fill(1,99).toString(),b.compare(Buffer.alloc(1),99),Buffer.from(new DataView(new ArrayBuffer(2))).length);console.log(b.write('x',0,1,{toString:function(){return 'utf8'}}),b.toString());for(var f of [function(){b.write('x',0,1,{})},function(){new File(undefined,'x')}])try{f()}catch(e){console.log(e.name,e.code)}`,
  `var b=Buffer.from([1,2]),from=Buffer.from,alloc=Buffer.alloc,compare=Buffer.compare;Buffer.from=Buffer.alloc=Buffer.compare=function(){throw Error('changed')};var equal=b.equals(b),size=new Blob([new Uint8Array([65])]).size,message='';try{Buffer('hi')}catch(e){message=e.message}Buffer.from=from;Buffer.alloc=alloc;Buffer.compare=compare;console.log(equal,size,message);`,
];

const blobStreamCases=[
 `(async function(){for(var text of [false,true]){var s=text?new Blob(['abc']).textStream():new Blob(['abc']).stream();console.log(s.constructor.name,Object.prototype.toString.call(s),s.locked);var r=s.getReader();console.log(r.constructor.name,s.locked);var a=await r.read();console.log(a.done,typeof a.value==='string'?a.value:Array.from(a.value).join());console.log((await r.read()).done);await r.closed;r.releaseLock();console.log(s.locked)}console.log((await new Blob([]).textStream().getReader().read()).done)})()`,
 `(async function(){var s=new Blob([new Uint8Array([1,2,3])]).stream(),r=s.getReader({mode:'byob'});for(var i=0;i<3;i++){var v=new Uint8Array(2),p=r.read(v);console.log(v.byteLength);var a=await p;console.log(a.done,a.value.constructor.name,Array.from(a.value).join())}r.releaseLock();console.log(s.locked);var q=new Blob(['x']).stream(),reader=q.getReader();await reader.cancel();console.log((await reader.read()).done);reader.releaseLock();console.log(q.locked)})()`,
 `(async function(){var b=new Blob(['hé😀'],{type:'TEXT/PLAIN'}),id=URL.createObjectURL(b),a=resolveObjectURL(id),c=resolveObjectURL(id);console.log(id.startsWith('blob:nodedata:'),a===b,a===c,a instanceof Blob,a.type,await a.text());console.log(resolveObjectURL(id+'?x#y').size,new URL(id).protocol,new URL(id).origin,new URL(id).toString()===id);URL.revokeObjectURL(id);console.log(resolveObjectURL(id),await a.text(),resolveObjectURL('missing'));console.log(URL.createObjectURL(b)!==URL.createObjectURL(b))})()`,
 `(async function(){var s=new Blob(['abc']).stream(),branches=s.tee();console.log(s.locked);for(var branch of branches){var r=branch.getReader(),a=await r.read();console.log(Buffer.from(a.value).toString(),(await r.read()).done);r.releaseLock()}var v=new Blob(['abc']).textStream(),it=v.values({preventCancel:true});console.log((await it.next()).value);await it.return();console.log(v.locked,(await v.getReader().read()).done)})()`,
 `(async function(){var b=new Blob([Buffer.alloc(65535,65),Buffer.from('😀é')]);for(var text of [false,true]){var r=(text?b.textStream():b.stream()).getReader(),total=0,tail='';while(true){var a=await r.read();if(a.done)break;total+=text?a.value.length:a.value.length;tail=text?a.value.slice(-3):Buffer.from(a.value).toString('hex').slice(-12)}console.log(text,total,tail)}})()`,
 `(async function(){var b=new Blob([new Uint8Array([0xef]),new Uint8Array([0xbb,0xbf,0xf0]),new Uint8Array([0x9f,0x98]),new Uint8Array([0x80,0xc3])]),r=b.textStream().getReader(),text='';while(true){var a=await r.read();if(a.done)break;text+=a.value}console.log(text);var s=new Blob(['abc']).stream(),q=s.getReader();for(var f of [function(){s.getReader()},function(){new Blob().textStream().getReader({mode:'byob'})}])try{f()}catch(e){console.log(e.name,e.code)}q.releaseLock();try{await q.read()}catch(e){console.log(e.name,e.code)}console.log(s.locked)})()`,
 `(async function(){for(var view of [new Uint16Array(2),new DataView(new ArrayBuffer(4))]){var r=new Blob([new Uint8Array([1,2]),new Uint8Array([3,4,5,6])]).stream().getReader({mode:'byob'}),a=await r.read(view,{min:2});console.log(a.value.constructor.name,a.value.byteLength,Buffer.from(a.value.buffer).toString('hex'),a.done);r.releaseLock()}for(var v of [new Uint8Array(0),{},new Uint8Array(new SharedArrayBuffer(2))])try{await new Blob(['x']).stream().getReader({mode:'byob'}).read(v)}catch(e){console.log(e.name,e.code)}var s=new Blob(['x']).stream();await s.cancel();var r=s.getReader();console.log((await r.read()).done);await r.closed;r.releaseLock();console.log(s.locked)})()`,
 `(async function(){var chunks=[],s=new Blob(['ab','cd']).textStream(),w=new WritableStream({write:function(chunk){return Promise.resolve().then(function(){chunks.push(chunk)})},close:function(){chunks.push('closed')}});await s.pipeTo(w);console.log(chunks.join(','),s.locked,w.locked);var a=new Blob(['x']).stream(),b=new WritableStream({write:function(){throw Error('sink failed')}});try{await a.pipeTo(b)}catch(e){console.log(e.message)}console.log(a.locked,b.locked,(await a.getReader().read()).done);var c=new Blob(['x']).stream(),d=new WritableStream({write:function(){throw Error('kept')}});try{await c.pipeTo(d,{preventCancel:true})}catch(e){console.log(e.message)}console.log(c.locked,d.locked);var e=new Blob(['x']).stream(),f=new WritableStream(),writer=f.getWriter();try{await e.pipeTo(f)}catch(error){console.log(error.name,error.code)}console.log(e.locked,f.locked);writer.releaseLock()})()`,
];
const signalFactory=`function createSignal(){var listeners=[],signal={aborted:false,reason:undefined,addEventListener:function(type,fn){listeners.push(fn)},removeEventListener:function(type,fn){listeners=listeners.filter(function(f){return f!==fn})}};return {signal:signal,abort:function(reason){signal.aborted=true;signal.reason=reason;for(var fn of listeners.slice())fn()}}}`;
blobStreamCases.push(signalFactory+`;(async function(){for(var prevent of [false,true]){var control=createSignal();control.abort(Error('already'));var aborted=false,w=new WritableStream({abort:function(e){aborted=e.message}}),s=new Blob(['x']).stream();try{await s.pipeTo(w,{signal:control.signal,preventCancel:prevent,preventAbort:prevent})}catch(e){console.log(e.message)}console.log(aborted,s.locked,w.locked,(await s.getReader().read()).done)}var controller=createSignal(),resolveWrite,startedResolve,started=new Promise(function(resolve){startedResolve=resolve}),events=[],target=new WritableStream({write:function(){events.push('write');startedResolve();return new Promise(function(resolve){resolveWrite=resolve})},abort:function(e){events.push(e.message)}}),source=new Blob(['x','y']).stream(),p=source.pipeTo(target,{signal:controller.signal});await started;controller.abort(Error('during'));resolveWrite();try{await p}catch(e){events.push(e.message)}console.log(events.join(','),source.locked,target.locked,(await source.getReader().read()).done)})()`);
function streamOracle(body:string){return runOracle(`var {resolveObjectURL}=require('node:buffer');`+body.replace(signalFactory,'function createSignal(){return new AbortController()}')).stdout}

export {cases,blobStreamCases,streamOracle};
